// OKF Workspace Generic - ChatPanel Component
// Chat interface with generic system prompt
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

import React, { useState, useEffect, useRef } from 'react';
import { C, btnStyle, Icon, LLM_API_URL, LLM_MODEL, LLM_API_KEY, RAG_API_URL } from '../constants';
import { fetchRagChunks, formatChunksForPrompt, buildSystemPrompt, getRagStatus, getRagIndicatorLabel } from '../utils/ragUtils';
import ChunksDrawer from './ChunksDrawer';

/**
 * ChatPanel - Chat interface with LLM
 * 
 * Features:
 * - Generic system prompt (no RCC-M references)
 * - Generic initial message
 * - Generic suggestions
 * - RAG integration with bundle support
 */
export default function ChatPanel({ 
  okfContent, 
  indexContent, 
  logContent, 
  onApplyEdit, 
  readOnly,
  meta,
  bundleConfig,
  activeOKF
}) {
  // ==========================================================================
  // STATE
  // ==========================================================================
  
  const [messages, setMessages] = useState([
    {
      role: 'assistant',
      content: `Bonjour ! Je suis votre assistant pour l'analyse de documentation technique.

Je peux vous aider à :

• **Modifier la fiche OKF** active
• **Mettre à jour index.md** (statut, liens, pages)
• **Ajouter une entrée dans log.md**
• **Interroger les documents PDF** pour des détails techniques

Que souhaitez-vous faire ?`
    }
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [ragStatus, setRagStatus] = useState(RAG_API_URL ? 'idle' : 'disabled');
  const [lastChunks, setLastChunks] = useState([]);
  const bottomRef = useRef(null);

  // ==========================================================================
  // EFFECTS
  // ==========================================================================
  
  // Auto-scroll to bottom when messages change
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // ==========================================================================
  // HANDLERS
  // ==========================================================================
  
  const sendMessage = async () => {
    if (!input.trim() || loading) return;
    
    const userMessage = input;
    const newMessages = [...messages, { role: 'user', content: userMessage }];
    setMessages(newMessages);
    setInput('');
    setLoading(true);
    setLastChunks([]);

    // -- 1. RETRIEVAL : build query from metadata and user message
    let chunks = [];
    if (RAG_API_URL) {
      setRagStatus('loading');
      chunks = await fetchRagChunks(meta, userMessage, bundleConfig);
      setLastChunks(chunks);
      setRagStatus(chunks.length > 0 ? 'ok' : 'error');
    }

    // -- 2. SYSTEM PROMPT : build generic system prompt
    const chunksBlock = formatChunksForPrompt(chunks);
    const systemPrompt = buildSystemPrompt(
      meta,
      okfContent || activeOKF?.content || '',
      indexContent,
      logContent,
      bundleConfig,
      chunksBlock,
      readOnly
    );

    // -- 3. APPEL LLM
    try {
      // Build request body based on provider
      const isMistral = LLM_API_URL.includes('mistral.ai');
      const isAnthropic = LLM_API_URL.includes('anthropic.com');
      const isOpenAI = LLM_API_URL.includes('openai.com');
      
      let requestBody;
      
      if (isAnthropic) {
        // Anthropic format: system as separate field, messages without system role
        requestBody = {
          model: LLM_MODEL,
          max_tokens: 2000,
          system: systemPrompt,
          messages: newMessages.map(m => ({ role: m.role, content: m.content })),
        };
      } else if (isMistral || isOpenAI) {
        // Mistral/OpenAI format: system as first message in messages array
        requestBody = {
          model: LLM_MODEL,
          max_tokens: 2000,
          messages: [
            { role: 'system', content: systemPrompt },
            ...newMessages.map(m => ({ role: m.role, content: m.content }))
          ],
        };
      } else {
        // Default: try Anthropic format first, then OpenAI
        requestBody = {
          model: LLM_MODEL,
          max_tokens: 2000,
          system: systemPrompt,
          messages: newMessages.map(m => ({ role: m.role, content: m.content })),
        };
      }
      
      const resp = await fetch(LLM_API_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(LLM_API_KEY ? { 'Authorization': `Bearer ${LLM_API_KEY}` } : {}),
        },
        body: JSON.stringify(requestBody),
      });
      
      if (!resp.ok) {
        const errorData = await resp.json().catch(() => ({}));
        const errorMsg = errorData.message || errorData.error?.message || resp.statusText;
        throw new Error(`HTTP ${resp.status}: ${errorMsg}`);
      }
      
      const data = await resp.json();
      
      // Check for API error responses
      if (data.error || data.message) {
        throw new Error(data.error?.message || data.message || 'Erreur API');
      }
      
      // Parse response based on provider
      let text;
      if (isMistral) {
        // Mistral response: { choices: [{ message: { content: "..." } }] }
        text = data.choices?.[0]?.message?.content;
      } else if (isAnthropic) {
        // Anthropic response: { content: [{ text: "..." }] }
        text = data.content?.[0]?.text;
      } else {
        // OpenAI response: { choices: [{ message: { content: "..." } }] }
        text = data.choices?.[0]?.message?.content;
      }
      
      if (!text) {
        console.error('Failed to parse LLM response:', data);
        throw new Error(`Format de réponse inattendu. Données reçues: ${JSON.stringify(data).substring(0, 200)}`);
      }

      // Parse edits if present
      const editsMatch = text.match(/<EDITS>([\s\S]*?)<\/EDITS>/);
      let edits = null;
      let displayText = text;
      if (editsMatch) {
        try {
          edits = JSON.parse(editsMatch[1].trim());
          displayText = text.replace(/<EDITS>[\s\S]*?<\/EDITS>/, '').trim();
        } catch {}
      }

      setMessages(prev => [...prev, { role: 'assistant', content: displayText, edits, chunks }]);
    } catch (err) {
      setMessages(prev => [...prev, { role: 'assistant', content: `Erreur : ${err.message}` }]);
    }
    
    setLoading(false);
  };

  const applyEdits = (edits) => {
    onApplyEdit(edits);
    setMessages(prev => [...prev, {
      role: 'assistant',
      content: `✅ Modifications appliquées :\n${edits.summary || 'Fichiers mis à jour.'}`
    }]);
  };

  const renderMessage = (msg, i) => {
    const isUser = msg.role === 'user';
    const lines = msg.content.split('\n');
    
    return (
      <div key={i} style={{
        marginBottom: 16,
        display: 'flex',
        flexDirection: isUser ? 'row-reverse' : 'row',
        gap: 8,
        alignItems: 'flex-start'
      }}>
        <div style={{
          width: 28,
          height: 28,
          borderRadius: '50%',
          flexShrink: 0,
          background: isUser ? C.blueDim : `${C.amber}22`,
          border: `1px solid ${isUser ? C.blue : C.amber}44`,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          fontSize: 10,
          fontWeight: 700,
          color: isUser ? C.blue : C.amber
        }}>
          {isUser ? 'MOI' : 'AI'}
        </div>
        
        <div style={{
          maxWidth: '85%',
          display: 'flex',
          flexDirection: 'column',
          gap: 6,
          alignItems: isUser ? 'flex-end' : 'flex-start'
        }}>
          <div style={{
            background: isUser ? C.blueDim : C.surface,
            border: `1px solid ${isUser ? `${C.blue}44` : C.border}`,
            borderRadius: isUser ? '12px 4px 12px 12px' : '4px 12px 12px 12px',
            padding: '10px 14px',
            fontSize: 13,
            color: C.text,
            lineHeight: 1.6
          }}>
            {lines.map((line, j) => {
              if (line.startsWith('**') && line.endsWith('**')) {
                return (
                  <div key={j} style={{ fontWeight: 700, color: isUser ? C.blue : C.amber, marginBottom: 2 }}>
                    {line.slice(2, -2)}
                  </div>
                );
              }
              if (line.startsWith('• ') || line.startsWith('- ')) {
                return (
                  <div key={j} style={{ paddingLeft: 12, color: C.muted }}>
                    • {line.slice(2)}
                  </div>
                );
              }
              if (line.startsWith('✅')) {
                return (
                  <div key={j} style={{ color: C.green }}>
                    {line}
                  </div>
                );
              }
              if (line === '') return <div key={j} style={{ height: 6 }} />;
              
              const parts = line.split(/(\*\*.*?\*\*)/);
              return (
                <div key={j}>
                  {parts.map((p, k) => 
                    p.startsWith('**') && p.endsWith('**') 
                      ? <strong key={k} style={{ color: C.amber }}>{p.slice(2, -2)}</strong>
                      : p
                  )}
                </div>
              );
            })}
          </div>

          {/* Sources RAG citées dans ce message */}
          {!isUser && msg.chunks?.length > 0 && (
            <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
              {msg.chunks.map((c, ci) => (
                <span key={ci} style={{
                  fontSize: 10,
                  color: C.teal,
                  background: `${C.teal}11`,
                  border: `1px solid ${C.teal}33`,
                  borderRadius: 4,
                  padding: '1px 6px',
                  fontFamily: 'monospace'
                }}>
                  📄 {c.ref} p.{c.page_start}
                </span>
              ))}
            </div>
          )}

          {msg.edits && (
            <div style={{
              background: `${C.green}11`,
              border: `1px solid ${C.green}44`,
              borderRadius: 8,
              padding: '8px 12px',
              width: '100%'
            }}>
              <div style={{ fontSize: 11, color: C.green, marginBottom: 6, fontWeight: 700 }}>
                MODIFICATIONS PROPOSÉES
              </div>
              <div style={{ fontSize: 12, color: C.muted, marginBottom: 8 }}>
                {msg.edits.summary}
              </div>
              <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                {msg.edits.fiche && (
                  <span style={{
                    fontSize: 10,
                    color: C.amber,
                    background: `${C.amber}11`,
                    borderRadius: 4,
                    padding: '2px 6px'
                  }}>
                    📝 fiche.md
                  </span>
                )}
                {msg.edits.index && (
                  <span style={{
                    fontSize: 10,
                    color: C.blue,
                    background: `${C.blue}11`,
                    borderRadius: 4,
                    padding: '2px 6px'
                  }}>
                    📋 index.md
                  </span>
                )}
                {msg.edits.log && (
                  <span style={{
                    fontSize: 10,
                    color: C.purple,
                    background: `${C.purple}11`,
                    borderRadius: 4,
                    padding: '2px 6px'
                  }}>
                    📒 log.md
                  </span>
                )}
              </div>
              <button
                onClick={() => applyEdits(msg.edits)}
                disabled={readOnly}
                style={{
                  ...btnStyle('primary'),
                  marginTop: 8,
                  width: '100%',
                  justifyContent: 'center',
                  opacity: readOnly ? 0.4 : 1,
                  cursor: readOnly ? 'not-allowed' : 'pointer'
                }}
              >
                {readOnly ? '🔒 Modifications désactivées' : <><Icon.check /> Appliquer les modifications</>}
              </button>
            </div>
          )}
        </div>
      </div>
    );
  };

  // ==========================================================================
  // RENDER
  // ==========================================================================

  const genericSuggestions = readOnly
    ? [
        'Résume cette fiche',
        'Quelles sont les exigences clés ?',
        "Quelles sont les références documentaires ?",
        'Vérifie la cohérence des liens'
      ]
    : [
        'Met à jour le statut en VALIDATED',
        "Ajoute une entrée dans log.md",
        'Vérifie la cohérence des liens',
        'Met à jour les références'
      ];

  return (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      height: '100%',
      background: C.bg
    }}>
      {/* Header */}
      <div style={{
        padding: '8px 12px',
        background: C.surface,
        borderBottom: `1px solid ${C.border}`,
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        flexShrink: 0
      }}>
        <Icon.chat />
        <span style={{ fontFamily: 'monospace', fontSize: 12, color: C.text }}>
          Assistant Technique
        </span>
        
        {/* RAG Indicator */}
        <div style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: 4,
          fontSize: 10,
          color: getRagStatus(RAG_API_URL, lastChunks, loading) === 'ok' ? C.teal :
                 getRagStatus(RAG_API_URL, lastChunks, loading) === 'loading' ? C.amber : C.muted,
          fontFamily: 'monospace'
        }}>
          <Icon.rag /> {getRagIndicatorLabel(ragStatus, lastChunks.length)}
        </div>

        <span style={{
          marginLeft: 'auto',
          width: 8,
          height: 8,
          borderRadius: '50%',
          background: C.green,
          boxShadow: `0 0 6px ${C.green}`
        }} />
      </div>

      {/* Messages */}
      <div style={{
        flex: 1,
        overflowY: 'auto',
        padding: '16px 12px'
      }}>
        {messages.map((m, i) => renderMessage(m, i))}
        
        {loading && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {ragStatus === 'loading' && (
              <div style={{
                display: 'flex',
                gap: 6,
                alignItems: 'center',
                fontSize: 11,
                color: C.teal
              }}>
                <Icon.rag />
                <span>Interrogation des documents…</span>
              </div>
            )}
            <div style={{
              display: 'flex',
              gap: 8,
              alignItems: 'center',
              color: C.muted,
              fontSize: 12
            }}>
              <div style={{ display: 'flex', gap: 3 }}>
                {[0, 1, 2].map(i => (
                  <div key={i} style={{
                    width: 6,
                    height: 6,
                    borderRadius: '50%',
                    background: C.amber,
                    animation: `pulse 1s ease-in-out ${i * 0.2}s infinite`
                  }} />
                ))}
              </div>
              <span>Analyse en cours…</span>
            </div>
          </div>
        )}
        <div ref={bottomRef} />
      </div>

      {/* Chunks drawer */}
      <ChunksDrawer
        chunks={lastChunks}
        ragStatus={loading && ragStatus === 'loading' ? 'loading' : 
                   (lastChunks.length > 0 ? 'ok' : ragStatus)}
        bundleConfig={bundleConfig}
      />

      {/* Suggestions */}
      {!loading && (
        <div style={{
          padding: '8px 12px',
          display: 'flex',
          gap: 6,
          flexWrap: 'wrap',
          borderTop: `1px solid ${C.border}`
        }}>
          {genericSuggestions.map((s, i) => (
            <button
              key={i}
              onClick={() => setInput(s)}
              style={{
                background: 'transparent',
                border: `1px solid ${C.border}`,
                color: C.muted,
                fontSize: 11,
                padding: '3px 10px',
                borderRadius: 12,
                cursor: 'pointer',
                transition: 'all .15s',
                fontFamily: 'system-ui'
              }}
              onMouseEnter={e => {
                e.currentTarget.style.borderColor = C.amber;
                e.currentTarget.style.color = C.amber;
              }}
              onMouseLeave={e => {
                e.currentTarget.style.borderColor = C.border;
                e.currentTarget.style.color = C.muted;
              }}
            >
              {s}
            </button>
          ))}
        </div>
      )}

      {/* Input */}
      <div style={{
        padding: '10px 12px',
        background: C.surface,
        borderTop: `1px solid ${C.border}`,
        display: 'flex',
        gap: 8,
        alignItems: 'flex-end',
        flexShrink: 0
      }}>
        <textarea
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={e => {
            if (e.key === 'Enter' && !e.shiftKey) {
              e.preventDefault();
              sendMessage();
            }
          }}
          placeholder={readOnly 
            ? 'Posez une question sur cette fiche… (Entrée)' 
            : 'Décrivez la modification souhaitée… (Entrée)'
          }
          rows={2}
          style={{
            flex: 1,
            background: C.bg,
            border: `1px solid ${C.border}`,
            borderRadius: 8,
            color: C.text,
            padding: '8px 12px',
            resize: 'none',
            fontFamily: 'system-ui',
            fontSize: 13,
            outline: 'none',
            lineHeight: 1.5
          }}
          onFocus={e => e.target.style.borderColor = readOnly ? C.amber : C.blue}
          onBlur={e => e.target.style.borderColor = C.border}
        />
        <button
          onClick={sendMessage}
          disabled={loading || !input.trim()}
          style={{
            ...btnStyle('primary'),
            padding: '10px 14px',
            opacity: (!input.trim() || loading) ? 0.5 : 1
          }}
        >
          <Icon.send />
        </button>
      </div>
    </div>
  );
}
