// OKF Workspace Generic - ChunksDrawer Component
// Displays RAG chunks with generic document context
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

import React, { useState } from 'react';
import { C, Icon } from '../constants';

/**
 * ChunksDrawer - Expandable drawer showing RAG chunks injected into context
 * Updated to show generic document context instead of RCC-M specific
 */
export default function ChunksDrawer({ chunks, ragStatus, bundleConfig }) {
  const [expanded, setExpanded] = useState(null);
  
  // Don't show if no chunks or RAG is idle/disabled
  if (ragStatus === 'idle' || ragStatus === 'disabled' || (!chunks.length && ragStatus !== 'loading')) {
    return null;
  }
  
  // Get PDF names from bundle config for display
  const pdfNames = bundleConfig?.pdfs?.map(p => p.name).join(', ') || 'Document';

  return (
    <div style={{
      borderTop: `1px solid ${C.teal}33`,
      background: `${C.teal}06`,
      flexShrink: 0,
      maxHeight: 220,
      display: 'flex',
      flexDirection: 'column'
    }}>
      {/* Drawer header */}
      <div style={{
        padding: '5px 12px',
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        borderBottom: `1px solid ${C.border}`,
        flexShrink: 0
      }}>
        <Icon.rag />
        <span style={{
          fontSize: 11,
          color: C.teal,
          fontFamily: 'monospace',
          fontWeight: 700
        }}>
          Contexte des documents injecté
        </span>
        <span style={{
          fontSize: 10,
          color: C.muted
        }}>
          {pdfNames && `— Référence: ${pdfNames}`}
        </span>
        {chunks.length > 0 && (
          <span style={{ fontSize: 10, color: C.muted }}>
            — {chunks.length} chunk{chunks.length > 1 ? 's' : ''} · cliquer pour développer
          </span>
        )}
      </div>

      {/* Chunk list */}
      <div style={{ overflowY: 'auto', flex: 1 }}>
        {ragStatus === 'loading' && (
          <div style={{
            padding: '8px 12px',
            display: 'flex',
            gap: 6,
            alignItems: 'center'
          }}>
            {[0, 1, 2].map(i => (
              <div key={i} style={{
                width: 5,
                height: 5,
                borderRadius: '50%',
                background: C.amber,
                animation: `pulse 1s ease-in-out ${i * 0.2}s infinite`
              }} />
            ))}
            <span style={{ fontSize: 11, color: C.muted }}>
              Interrogation des documents...
            </span>
          </div>
        )}
        
        {chunks.map((c, i) => (
          <div key={i}
            onClick={() => setExpanded(expanded === i ? null : i)}
            style={{
              padding: '5px 12px',
              borderBottom: `1px solid ${C.border}22`,
              cursor: 'pointer',
              userSelect: 'none'
            }}
            onMouseEnter={e => e.currentTarget.style.background = `${C.teal}08`}
            onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{
                fontSize: 10,
                color: C.teal,
                fontFamily: 'monospace',
                fontWeight: 700
              }}>
                {c.ref || `chunk-${i + 1}`}
              </span>
              <span style={{ fontSize: 10, color: C.muted }}>
                pp.{c.page_start}–{c.page_end}
              </span>
              <span style={{
                fontSize: 10,
                color: C.muted,
                flex: 1,
                overflow: 'hidden',
                textOverflow: 'ellipsis',
                whiteSpace: 'nowrap'
              }}>
                {c.text?.slice(0, 80)}…
              </span>
              {c.score != null && (
                <span style={{
                  fontSize: 10,
                  color: C.muted,
                  flexShrink: 0
                }}>
                  {c.score.toFixed(2)}
                </span>
              )}
            </div>
            {expanded === i && (
              <div style={{
                marginTop: 6,
                fontSize: 11,
                color: C.text,
                lineHeight: 1.55,
                fontFamily: 'monospace',
                whiteSpace: 'pre-wrap',
                background: C.bg,
                borderRadius: 4,
                padding: '8px 10px',
                border: `1px solid ${C.border}`
              }}>
                {c.text}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
