// OKF Workspace Generic - Header Component
// Main application header with generic text (no RCC-M)
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

import React from 'react';
import { C, btnStyle, Icon } from '../constants';
import StatusBadge from './StatusBadge';

/**
 * Header - Main application header
 * 
 * Features:
 * - Logo and app name (generic, no RCC-M)
 * - Active OKF ID badge
 * - RAG status indicator
 * - Read-only/Edit toggle
 * - Layout buttons
 * - New Bundle button
 */
export default function Header({
  meta,
  bundleConfig,
  setShowInitializer,
  readOnly,
  setReadOnly,
  setLayout,
  layout,
  RAG_API_URL,
  onSaveBundle,
  onLoadBundle
}) {
  const loadInputRef = React.useRef(null);

  // ==========================================================================
  // HANDLERS
  // ==========================================================================

  const handleLoadChange = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    Promise.resolve(onLoadBundle?.(file)).catch(err => {
      console.error('Failed to load bundle:', err);
    });
    // Allow re-selecting the same file later
    e.target.value = '';
  };

  // ==========================================================================
  // RENDER
  // ==========================================================================

  return (
    <div style={{
      display: 'flex',
      alignItems: 'center',
      gap: 12,
      padding: '0 16px',
      background: C.surface,
      borderBottom: `1px solid ${C.border}`,
      height: 44,
      flexShrink: 0
    }}>
      {/* Left: Logo and App Name */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        <div style={{
          width: 24,
          height: 24,
          borderRadius: 6,
          background: `${C.amber}22`,
          border: `1px solid ${C.amber}44`,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center'
        }}>
          <span style={{ fontSize: 12 }}>⚛</span>
        </div>
        <span style={{
          fontFamily: 'monospace',
          fontSize: 13,
          fontWeight: 700,
          color: C.amber
        }}>
          OKF Workspace
        </span>
      </div>

      {/* Center: Bundle Name */}
      {bundleConfig && (
        <div style={{
          display: 'flex',
          alignItems: 'center',
          gap: 6,
          padding: '2px 10px',
          background: `${C.blue}11`,
          borderRadius: 20,
          border: `1px solid ${C.blue}33`
        }}>
          <span style={{ fontSize: 11, color: C.blue, fontFamily: 'monospace' }}>
            {bundleConfig.name}
          </span>
        </div>
      )}

      {/* Center: Active OKF Badge */}
      {meta?.id && (
        <div style={{
          display: 'flex',
          alignItems: 'center',
          gap: 6,
          marginLeft: 8,
          padding: '2px 10px',
          background: `${C.blue}11`,
          borderRadius: 20,
          border: `1px solid ${C.blue}33`
        }}>
          <span style={{ fontSize: 11, color: C.blue, fontFamily: 'monospace' }}>
            {meta.id}
          </span>
          {(meta.status || meta.statut) && (
            <StatusBadge status={meta.status || meta.statut} />
          )}
        </div>
      )}

      {/* Right: RAG Status and Controls */}
      <div style={{ marginLeft: 'auto', display: 'flex', gap: 8, alignItems: 'center' }}>
        {/* RAG Status */}
        <span style={{
          fontSize: 10,
          fontFamily: 'monospace',
          color: RAG_API_URL ? C.teal : C.muted
        }}>
          {RAG_API_URL ? '⬡ RAG connecté' : '⬡ RAG non configuré'}
        </span>

        {/* New Bundle Button */}
        <button
          onClick={() => setShowInitializer(true)}
          style={btnStyle('primary')}
          title="Créer un nouveau bundle"
        >
          <span style={{ fontSize: 12 }}>➕ Nouveau Bundle</span>
        </button>

        {/* Save Bundle Button */}
        <button
          onClick={() => onSaveBundle?.()}
          disabled={!bundleConfig}
          style={{ ...btnStyle('secondary'), opacity: bundleConfig ? 1 : 0.5, cursor: bundleConfig ? 'pointer' : 'not-allowed' }}
          title="Sauvegarder le bundle (bundle.json)"
        >
          <Icon.save /> Sauvegarder
        </button>

        {/* Load Bundle Button */}
        <label
          style={{ ...btnStyle('secondary'), cursor: 'pointer' }}
          title="Charger un bundle (bundle.json)"
        >
          <Icon.upload /> Charger
          <input
            ref={loadInputRef}
            type="file"
            accept=".json,application/json"
            style={{ display: 'none' }}
            onChange={handleLoadChange}
          />
        </label>

        {/* Read-only / Edit Toggle */}
        <button
          onClick={() => setReadOnly(r => !r)}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            padding: '4px 12px',
            borderRadius: 20,
            fontSize: 11,
            fontFamily: 'monospace',
            cursor: 'pointer',
            border: '1px solid',
            transition: 'all .2s',
            background: readOnly ? `${C.amber}22` : 'transparent',
            borderColor: readOnly ? C.amber : C.border,
            color: readOnly ? C.amber : C.muted
          }}
        >
          <span style={{
            display: 'inline-block',
            width: 28,
            height: 16,
            borderRadius: 8,
            background: readOnly ? C.amber : C.border,
            position: 'relative',
            transition: 'background .2s',
            flexShrink: 0
          }}>
            <span style={{
              position: 'absolute',
              top: 2,
              left: readOnly ? 14 : 2,
              width: 12,
              height: 12,
              borderRadius: '50%',
              background: '#fff',
              transition: 'left .2s'
            }} />
          </span>
          {readOnly ? '🔒 Lecture' : '✏️ Édition'}
        </button>

        {/* Layout Buttons */}
        <div style={{
          width: 1,
          height: 20,
          background: C.border
        }} />
        
        {[['3col', '⊞'], ['focus-okf', '⊟'], ['focus-pdf', '⊠']].map(([k, icon]) => (
          <button
            key={k}
            onClick={() => setLayout(k)}
            title={k}
            style={{
              ...btnStyle('ghost'),
              padding: '4px 8px',
              color: layout === k ? C.blue : C.muted
            }}
          >
            {icon}
          </button>
        ))}
      </div>
    </div>
  );
}
