// OKF Workspace Generic - InitializerModal Component
// 4-step wizard for creating a new bundle
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

import React, { useState, useEffect, useCallback } from 'react';
import { C, btnStyle, Icon } from '../constants';
import { createBundleConfig } from '../utils/bundleStorage';

/**
 * InitializerModal - 4-step wizard for bundle creation
 * 
 * Steps:
 * 1. Folder selection
 * 2. Name and description
 * 3. PDF selection with page ranges
 * 4. Confirmation summary
 */
export default function InitializerModal({ onCreate, onClose, isOpen }) {
  // ==========================================================================
  // STATE
  // ==========================================================================
  
  const [step, setStep] = useState('folder'); // 'folder' | 'name' | 'pdfs' | 'confirm'
  const [selectedPath, setSelectedPath] = useState('');
  const [bundleName, setBundleName] = useState('');
  const [bundleDescription, setBundleDescription] = useState('');
  const [selectedPDFs, setSelectedPDFs] = useState([]); // Array of File objects
  const [pdfRanges, setPdfRanges] = useState({}); // { pdfId: { start: number, end: number } }
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // ==========================================================================
  // DERIVED STATE
  // ==========================================================================
  
  const canProceed = useCallback(() => {
    switch (step) {
      case 'folder':
        return selectedPath.trim() !== '';
      case 'name':
        return bundleName.trim() !== '' && /^[a-zA-Z0-9-_\s]+$/.test(bundleName.trim());
      case 'pdfs':
        return selectedPDFs.length > 0;
      case 'confirm':
        return true;
      default:
        return false;
    }
  }, [step, selectedPath, bundleName, selectedPDFs.length]);
  
  const steps = [
    { id: 'folder', label: '📁 Dossier', description: 'Sélectionner le dossier de travail' },
    { id: 'name', label: '✍️ Nom', description: 'Nom et description du bundle' },
    { id: 'pdfs', label: '📄 PDFs', description: 'Sélectionner les PDFs de référence' },
    { id: 'confirm', label: '✅ Confirmation', description: 'Résumé et création' }
  ];
  
  const currentStepIndex = steps.findIndex(s => s.id === step);

  // ==========================================================================
  // EFFECTS
  // ==========================================================================
  
  // Reset state when modal closes
  useEffect(() => {
    if (!isOpen) {
      setStep('folder');
      setSelectedPath('');
      setBundleName('');
      setBundleDescription('');
      setSelectedPDFs([]);
      setPdfRanges({});
      setError(null);
      setLoading(false);
    }
  }, [isOpen]);

  // ==========================================================================
  // HANDLERS
  // ==========================================================================
  
  const handleClose = () => {
    setError(null);
    onClose();
  };
  
  const handleNext = () => {
    if (!canProceed()) return;
    
    // Validate before proceeding
    if (step === 'name' && !/^[a-zA-Z0-9-_\s]+$/.test(bundleName.trim())) {
      setError('Le nom du bundle ne doit contenir que des lettres, chiffres, tirets et underscores');
      return;
    }
    
    setError(null);
    const nextStepIndex = currentStepIndex + 1;
    if (nextStepIndex < steps.length) {
      setStep(steps[nextStepIndex].id);
    } else {
      // Create bundle
      handleCreate();
    }
  };
  
  const handleBack = () => {
    if (step === 'folder') {
      handleClose();
      return;
    }
    const prevStepIndex = currentStepIndex - 1;
    if (prevStepIndex >= 0) {
      setStep(steps[prevStepIndex].id);
    }
  };
  
  const handleCreate = async () => {
    setLoading(true);
    setError(null);
    
    try {
      // Build PDF references
      const pdfRefs = selectedPDFs.map((file, index) => {
        const range = pdfRanges[file.name] || { start: 1, end: 100 };
        return {
          id: `pdf-${Date.now()}-${index}`,
          name: file.name,
          path: selectedPath ? `${selectedPath}/${file.name}` : file.name,
          pages: {
            start: range.start,
            end: range.end,
            raw: `${range.start}-${range.end}`
          }
        };
      });
      
      // Create bundle config
      const bundleConfig = createBundleConfig({
        name: bundleName.trim(),
        description: bundleDescription.trim() || undefined,
        path: selectedPath,
        pdfs: pdfRefs.map(p => ({ name: p.name, pageRange: p.pages }))
      });
      
      // Update bundle config with actual PDF refs
      bundleConfig.pdfs = pdfRefs;
      
      // Create initial OKF file with minimal content
      // Use first PDF as reference if available, otherwise empty
      const firstPDF = selectedPDFs[0];
      const firstPDFRef = pdfRefs[0];
      const okfId = `OKF-${Date.now()}`;
      const initialOKFFiles = [
        {
          id: okfId,
          title: 'Nouvelle fiche',
          ref_document: firstPDF ? firstPDF.name : '',
          pages: firstPDFRef ? firstPDFRef.pages : { start: 1, end: 100, raw: '1-100' },
          status: 'DRAFT',
          version: '1.0',
          author: '',
          tags: [],
          related: [],
          content: `---
id: ${okfId}
title: Nouvelle fiche
ref_document: ${firstPDF ? firstPDF.name : ''}
pages: ${firstPDFRef ? firstPDFRef.pages.raw : '1-100'}
status: DRAFT
version: 1.0
---

# ${okfId} — Nouvelle fiche

## Objet

## Domaine d'application

## Exigences principales

## Actions en cours

## Historique
`
        }
      ];
      
      // Call onCreate with the new bundle
      onCreate({
        bundleConfig,
        okfFiles: initialOKFFiles,
        pdfFiles: Object.fromEntries(
          selectedPDFs.map((file, index) => [
            pdfRefs[index].id,
            { file, url: URL.createObjectURL(file) }
          ])
        )
      });
      
      setLoading(false);
      onClose();
    } catch (err) {
      setError(`Échec de la création du bundle: ${err.message}`);
      setLoading(false);
    }
  };
  
  const handlePDFSelect = (e) => {
    const files = Array.from(e.target.files);
    if (files.length === 0) return;
    
    setSelectedPDFs(prev => {
      // Avoid duplicates
      const existingNames = new Set(prev.map(f => f.name));
      const newFiles = files.filter(f => !existingNames.has(f.name));
      return [...prev, ...newFiles];
    });
  };
  
  const handleRemovePDF = (index) => {
    const file = selectedPDFs[index];
    setSelectedPDFs(prev => prev.filter((_, i) => i !== index));
    setPdfRanges(prev => {
      const newRanges = { ...prev };
      delete newRanges[file.name];
      return newRanges;
    });
  };
  
  const handlePageRangeChange = (fileName, field, value) => {
    setPdfRanges(prev => ({
      ...prev,
      [fileName]: {
        ...prev[fileName],
        [field]: Number(value) || 1
      }
    }));
  };

  // ==========================================================================
  // RENDER
  // ==========================================================================
  
  if (!isOpen) return null;

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'rgba(0, 0, 0, 0.8)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 10000,
      padding: 20
    }} onClick={handleClose}>
      <div style={{
        background: C.surface,
        borderRadius: 8,
        border: `1px solid ${C.border}`,
        width: '100%',
        maxWidth: 600,
        maxHeight: '90vh',
        overflow: 'auto',
        display: 'flex',
        flexDirection: 'column'
      }} onClick={e => e.stopPropagation()}>
        
        {/* Header */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '12px 16px',
          borderBottom: `1px solid ${C.border}`,
          background: C.bg
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ fontSize: 18, color: C.amber }}>⚡</span>
            <span style={{ fontSize: 14, fontWeight: 700, color: C.text, fontFamily: 'monospace' }}>
              Créer un nouveau Bundle OKF
            </span>
          </div>
          <button onClick={handleClose} style={btnStyle('ghost')}>
            <span style={{ fontSize: 18 }}>×</span>
          </button>
        </div>
        
        {/* Progress bar */}
        <div style={{
          display: 'flex',
          padding: '8px 16px',
          gap: 8,
          borderBottom: `1px solid ${C.border}`
        }}>
          {steps.map((s, index) => (
            <div key={s.id} style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              flex: 1
            }}>
              <div style={{
                width: '100%',
                height: 4,
                background: index <= currentStepIndex ? C.amber : C.border,
                borderRadius: 2,
                transition: 'background 0.3s'
              }} />
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: 4,
                marginTop: 8,
                fontSize: 11
              }}>
                <span style={{ color: index <= currentStepIndex ? C.amber : C.muted }}>
                  {s.label}
                </span>
                <span style={{ color: C.muted, fontSize: 10 }}>
                  {index + 1}/{steps.length}
                </span>
              </div>
            </div>
          ))}
        </div>
        
        {/* Content */}
        <div style={{ flex: 1, padding: '16px 20px', overflowY: 'auto' }}>
          
          {/* Step 1: Folder */}
          {step === 'folder' && (
            <div>
              <h3 style={{ color: C.text, fontSize: 14, marginBottom: 8, fontFamily: 'system-ui' }}>
                Étape 1 : Sélectionner le dossier de travail
              </h3>
              <p style={{ color: C.muted, fontSize: 12, marginBottom: 16 }}>
                Choisissez un dossier local où les PDFs et fiches OKF seront référencés.
              </p>
              
              <div style={{ marginBottom: 16 }}>
                <input
                  type="text"
                  value={selectedPath}
                  onChange={(e) => setSelectedPath(e.target.value)}
                  placeholder="Chemin du dossier (ex: /home/user/Documents/Projets/ISO_9001)"
                  style={{
                    width: '100%',
                    background: C.bg,
                    border: `1px solid ${C.border}`,
                    color: C.text,
                    padding: '8px 12px',
                    borderRadius: 6,
                    fontFamily: 'monospace',
                    fontSize: 12
                  }}
                />
                <p style={{ fontSize: 11, color: C.muted, marginTop: 4 }}>
                  Entrez le chemin absolu ou relatif du dossier contenant vos PDFs
                </p>
              </div>
              
              {selectedPath && (
                <div style={{
                  background: C.bg,
                  border: `1px solid ${C.border}`,
                  borderRadius: 6,
                  padding: '8px 12px',
                  fontFamily: 'monospace',
                  fontSize: 11,
                  color: C.text,
                  wordBreak: 'break-all'
                }}>
                  Dossier sélectionné: {selectedPath}
                </div>
              )}
            </div>
          )}
          
          {/* Step 2: Name */}
          {step === 'name' && (
            <div>
              <h3 style={{ color: C.text, fontSize: 14, marginBottom: 8, fontFamily: 'system-ui' }}>
                Étape 2 : Nom et description du bundle
              </h3>
              <p style={{ color: C.muted, fontSize: 12, marginBottom: 16 }}>
                Donnez un nom unique à votre bundle et une description optionnelle.
              </p>
              
              <div style={{ marginBottom: 16 }}>
                <label style={{
                  display: 'block',
                  fontSize: 11,
                  color: C.text,
                  marginBottom: 4,
                  fontFamily: 'system-ui'
                }}>
                  Nom du bundle *
                </label>
                <input
                  type="text"
                  value={bundleName}
                  onChange={(e) => {
                    setBundleName(e.target.value);
                    if (error && /^[a-zA-Z0-9-_\s]*$/.test(e.target.value)) {
                      setError(null);
                    }
                  }}
                  placeholder="ex: Normes ISO 9001"
                  style={{
                    width: '100%',
                    background: C.bg,
                    border: error && bundleName ? `1px solid ${C.red}` : `1px solid ${C.border}`,
                    color: C.text,
                    padding: '8px 12px',
                    borderRadius: 6,
                    fontFamily: 'monospace',
                    fontSize: 13
                  }}
                />
                {error && bundleName && (
                  <span style={{ color: C.red, fontSize: 11, marginTop: 4, display: 'block' }}>
                    {error}
                  </span>
                )}
                <span style={{ fontSize: 10, color: C.muted, marginTop: 4, display: 'block' }}>
                  Caractères autorisés: lettres, chiffres, tirets, underscores, espaces
                </span>
              </div>
              
              <div>
                <label style={{
                  display: 'block',
                  fontSize: 11,
                  color: C.text,
                  marginBottom: 4,
                  fontFamily: 'system-ui'
                }}>
                  Description (optionnelle)
                </label>
                <textarea
                  value={bundleDescription}
                  onChange={(e) => setBundleDescription(e.target.value)}
                  placeholder="ex: Système de management de la qualité"
                  rows={3}
                  style={{
                    width: '100%',
                    background: C.bg,
                    border: `1px solid ${C.border}`,
                    color: C.text,
                    padding: '8px 12px',
                    borderRadius: 6,
                    fontFamily: 'monospace',
                    fontSize: 12,
                    resize: 'none'
                  }}
                />
              </div>
            </div>
          )}
          
          {/* Step 3: PDFs */}
          {step === 'pdfs' && (
            <div>
              <h3 style={{ color: C.text, fontSize: 14, marginBottom: 8, fontFamily: 'system-ui' }}>
                Étape 3 : Sélectionner les PDFs de référence
              </h3>
              <p style={{ color: C.muted, fontSize: 12, marginBottom: 16 }}>
                Chargez un ou plusieurs fichiers PDF qui serviront de référence pour ce bundle.
              </p>
              
              {/* File input */}
              <label style={{
                ...btnStyle('primary'),
                display: 'block',
                width: '100%',
                justifyContent: 'center',
                padding: '12px 16px',
                marginBottom: 16
              }}>
                <Icon.upload /> Ajouter des PDFs
                <input
                  type="file"
                  accept=".pdf"
                  multiple
                  onChange={handlePDFSelect}
                  style={{ display: 'none' }}
                />
              </label>
              
              {/* Selected PDFs */}
              {selectedPDFs.length > 0 && (
                <div>
                  <h4 style={{ color: C.muted, fontSize: 11, marginBottom: 8, fontFamily: 'system-ui' }}>
                    PDFs sélectionnés ({selectedPDFs.length})
                  </h4>
                  <div style={{
                    display: 'flex',
                    flexDirection: 'column',
                    gap: 8
                  }}>
                    {selectedPDFs.map((file, index) => (
                      <div key={file.name} style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: 8,
                        background: C.bg,
                        border: `1px solid ${C.border}`,
                        borderRadius: 6,
                        padding: '8px 12px'
                      }}>
                        <Icon.pdf />
                        <div style={{ flex: 1, minWidth: 0 }}>
                          <div style={{
                            fontFamily: 'monospace',
                            fontSize: 12,
                            color: C.text,
                            whiteSpace: 'nowrap',
                            overflow: 'hidden',
                            textOverflow: 'ellipsis'
                          }}>
                            {file.name}
                          </div>
                          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 4 }}>
                            <span style={{ fontSize: 10, color: C.muted }}>Pages:</span>
                            <input
                              type="number"
                              value={pdfRanges[file.name]?.start || 1}
                              onChange={(e) => handlePageRangeChange(file.name, 'start', e.target.value)}
                              min="1"
                              style={{
                                width: 50,
                                background: C.surface,
                                border: `1px solid ${C.border}`,
                                color: C.text,
                                padding: '2px 6px',
                                borderRadius: 4,
                                fontFamily: 'monospace',
                                fontSize: 11
                              }}
                            />
                            <span style={{ fontSize: 10, color: C.muted }}>à</span>
                            <input
                              type="number"
                              value={pdfRanges[file.name]?.end || 100}
                              onChange={(e) => handlePageRangeChange(file.name, 'end', e.target.value)}
                              min="1"
                              style={{
                                width: 50,
                                background: C.surface,
                                border: `1px solid ${C.border}`,
                                color: C.text,
                                padding: '2px 6px',
                                borderRadius: 4,
                                fontFamily: 'monospace',
                                fontSize: 11
                              }}
                            />
                          </div>
                        </div>
                        <button
                          onClick={() => handleRemovePDF(index)}
                          style={{
                            background: 'transparent',
                            border: 'none',
                            cursor: 'pointer',
                            color: C.red,
                            padding: 4,
                            borderRadius: 4
                          }}
                          title="Supprimer"
                        >
                          ×
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}
              
              {selectedPDFs.length === 0 && (
                <div style={{
                  textAlign: 'center',
                  padding: '32px 16px',
                  color: C.muted,
                  fontSize: 12
                }}>
                  <Icon.pdf />
                  <p style={{ marginTop: 8 }}>Aucun PDF sélectionné</p>
                  <p style={{ fontSize: 10, marginTop: 4 }}>
                    Ajoutez au moins un PDF pour continuer
                  </p>
                </div>
              )}
            </div>
          )}
          
          {/* Step 4: Confirm */}
          {step === 'confirm' && (
            <div>
              <h3 style={{ color: C.text, fontSize: 14, marginBottom: 8, fontFamily: 'system-ui' }}>
                Étape 4 : Résumé et confirmation
              </h3>
              <p style={{ color: C.muted, fontSize: 12, marginBottom: 16 }}>
                Vérifiez les informations avant de créer le bundle.
              </p>
              
              <div style={{
                background: C.bg,
                border: `1px solid ${C.border}`,
                borderRadius: 6,
                padding: '16px',
                marginBottom: 16
              }}>
                <div style={{ marginBottom: 12 }}>
                  <span style={{ fontSize: 10, color: C.muted, fontFamily: 'monospace' }}>DOSSIER</span>
                  <div style={{ fontFamily: 'monospace', color: C.text, marginTop: 4 }}>
                    {selectedPath || '(Non spécifié)'}
                  </div>
                </div>
                
                <div style={{ marginBottom: 12 }}>
                  <span style={{ fontSize: 10, color: C.muted, fontFamily: 'monospace' }}>NOM DU BUNDLE</span>
                  <div style={{ fontFamily: 'monospace', color: C.amber, fontSize: 14, marginTop: 4 }}>
                    {bundleName}
                  </div>
                </div>
                
                {bundleDescription && (
                  <div style={{ marginBottom: 12 }}>
                    <span style={{ fontSize: 10, color: C.muted, fontFamily: 'monospace' }}>DESCRIPTION</span>
                    <div style={{ color: C.text, marginTop: 4 }}>
                      {bundleDescription}
                    </div>
                  </div>
                )}
                
                <div>
                  <span style={{ fontSize: 10, color: C.muted, fontFamily: 'monospace' }}>PDFs</span>
                  <div style={{ marginTop: 4 }}>
                    {selectedPDFs.map((file, index) => (
                      <div key={file.name} style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: 8,
                        fontFamily: 'monospace',
                        fontSize: 11,
                        color: C.text
                      }}>
                        <span style={{ color: C.blue }}>•</span>
                        <span>{file.name}</span>
                        <span style={{ color: C.muted }}>
                          (pp. {pdfRanges[file.name]?.start || 1}-{pdfRanges[file.name]?.end || 100})
                        </span>
                      </div>
                    ))}
                  </div>
                  <div style={{ marginTop: 4, fontSize: 10, color: C.muted }}>
                    {selectedPDFs.length} fichier{selectedPDFs.length > 1 ? 's' : ''}
                  </div>
                </div>
              </div>
            </div>
          )}
          
          {/* Error message */}
          {error && step !== 'name' && (
            <div style={{
              background: `${C.red}11`,
              border: `1px solid ${C.red}33`,
              borderRadius: 6,
              padding: '8px 12px',
              marginBottom: 16,
              color: C.red,
              fontSize: 12
            }}>
              {error}
            </div>
          )}
        </div>
        
        {/* Footer buttons */}
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          padding: '12px 16px',
          borderTop: `1px solid ${C.border}`,
          background: C.bg
        }}>
          <button
            onClick={handleBack}
            disabled={loading}
            style={{
              ...btnStyle('secondary'),
              opacity: loading ? 0.5 : 1
            }}
          >
            {step === 'folder' ? 'Annuler' : '← Retour'}
          </button>
          
          <button
            onClick={handleNext}
            disabled={loading || !canProceed()}
            style={{
              ...btnStyle('primary'),
              opacity: (loading || !canProceed()) ? 0.5 : 1
            }}
          >
            {loading ? (
              <>
                <span className="spinner" style={{ width: 14, height: 14, border: '2px solid transparent', borderTopColor: 'currentColor', borderRadius: '50%', animation: 'spin 0.8s linear infinite' }} />
                Création...
              </>
            ) : step === 'confirm' ? (
              '✅ Créer le Bundle'
            ) : (
              'Suivant →'
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
