// OKF Workspace Generic - MarkdownPreview Component
// Renders markdown content with inline styles
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

import React from 'react';
import { C } from '../constants';
import { stripFrontMatter } from '../utils/parseFrontMatter';

/**
 * MarkdownPreview - Renders markdown content line by line
 * Supports:
 * - Headings (h1, h2, h3)
 * - Tables
 * - Lists (ordered, unordered, task lists)
 * - Bold text (**bold**)
 * - Empty lines
 */
export default function MarkdownPreview({ content }) {
  if (!content) return null;
  
  // Strip front-matter
  const strippedContent = stripFrontMatter(content);
  const lines = strippedContent.split('\n');
  
  return (
    <div style={{
      fontFamily: 'monospace',
      lineHeight: 1.7,
      color: C.text,
      fontSize: 14
    }}>
      {lines.map((line, i) => {
        // Headings
        if (line.startsWith('### ')) {
          return (
            <h3 key={i} style={{
              color: C.blue,
              fontSize: 14,
              marginTop: 16,
              marginBottom: 4
            }}>
              {line.slice(4)}
            </h3>
          );
        }
        if (line.startsWith('## ')) {
          return (
            <h2 key={i} style={{
              color: C.text,
              fontSize: 16,
              borderBottom: `1px solid ${C.border}`,
              paddingBottom: 4,
              marginTop: 20
            }}>
              {line.slice(3)}
            </h2>
          );
        }
        if (line.startsWith('# ')) {
          return (
            <h1 key={i} style={{
              color: C.amber,
              fontSize: 18,
              marginBottom: 12
            }}>
              {line.slice(2)}
            </h1>
          );
        }
        
        // Tables
        if (line.startsWith('| ')) {
          if (/^[| -]+$/.test(line)) return null; // Skip separator lines
          const cells = line.split('|').filter(c => c.trim());
          return (
            <div key={i} style={{
              display: 'grid',
              gridTemplateColumns: `repeat(${cells.length}, 1fr)`,
              borderBottom: `1px solid ${C.border}26`
            }}>
              {cells.map((c, j) => (
                <div key={j} style={{
                  padding: '3px 8px',
                  fontSize: 12,
                  color: j === 0 ? C.amber : C.text,
                  fontFamily: 'monospace'
                }}>
                  {c.trim()}
                </div>
              ))}
            </div>
          );
        }
        
        // Task lists
        if (line.startsWith('- [ ]')) {
          return (
            <div key={i} style={{
              display: 'flex',
              gap: 8,
              alignItems: 'center',
              color: C.muted,
              fontSize: 13
            }}>
              <span style={{ color: C.amber }}>☐</span>
              {line.slice(6)}
            </div>
          );
        }
        if (line.startsWith('- [x]')) {
          return (
            <div key={i} style={{
              display: 'flex',
              gap: 8,
              alignItems: 'center',
              color: C.muted,
              fontSize: 13
            }}>
              <span style={{ color: C.green }}>☑</span>
              {line.slice(6)}
            </div>
          );
        }
        
        // Unordered lists
        if (line.startsWith('- ')) {
          return (
            <div key={i} style={{
              paddingLeft: 16,
              color: C.text,
              fontSize: 13
            }}>
              • {line.slice(2)}
            </div>
          );
        }
        
        // Ordered lists
        if (/^\d+\. /.test(line)) {
          return (
            <div key={i} style={{
              paddingLeft: 16,
              color: C.text,
              fontSize: 13
            }}>
              {line}
            </div>
          );
        }
        
        // Empty lines
        if (line.trim() === '') {
          return <div key={i} style={{ height: 8 }} />;
        }
        
        // Default: paragraph
        return (
          <p key={i} style={{
            margin: '4px 0',
            fontSize: 13,
            color: C.text,
            lineHeight: 1.7
          }}>
            {line}
          </p>
        );
      })}
    </div>
  );
}
