// OKF Workspace Generic - OKFPanel Component
// OKF file editor with generic metadata fields
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

import React, { useState, useEffect } from 'react';
import { C, btnStyle, Icon, STATUS_LABELS } from '../constants';
import { parseFrontMatter, stripFrontMatter } from '../utils/parseFrontMatter';
import StatusBadge from './StatusBadge';
import MarkdownPreview from './MarkdownPreview';

/**
 * OKFPanel - Editor for OKF files with generic metadata
 * 
 * Features:
 * - Generic metadata fields (ref_document, pages, status, etc.)
 * - Support for both old (RCC-M) and new field names
 * - Edit and preview tabs
 * - File save/load
 */
export default function OKFPanel({ 
  content, 
  onChange, 
  meta,
  readOnly,
  activeOKF,
  bundleConfig
}) {
  // ==========================================================================
  // STATE
  // ==========================================================================
  
  const [tab, setTab] = useState(readOnly ? 'preview' : 'edit');
  const [copied, setCopied] = useState(false);
  const fileInputRef = React.useRef(null);

  // ==========================================================================
  // EFFECTS
  // ==========================================================================
  
  // Force preview tab when readOnly changes to true
  useEffect(() => {
    if (readOnly) {
      setTab('preview');
    }
  }, [readOnly]);

  // ==========================================================================
  // HANDLERS
  // ==========================================================================
  
  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };
  
  const handleFileLoad = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = ev => onChange(ev.target.result);
    reader.readAsText(file);
  };
  
  const handleSave = () => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `${meta?.id || activeOKF?.id || 'fiche'}.md`;
    a.click();
  };

  // ==========================================================================
  // RENDER
  // ==========================================================================

  return (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      height: '100%',
      background: C.bg
    }}>
      {/* Header */}
      <div style={{
        padding: '8px 12px',
        background: C.surface,
        borderBottom: `1px solid ${C.border}`,
        flexShrink: 0
      }}>
        <div style={{
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          marginBottom: 6
        }}>
          <Icon.file />
          <span style={{
            fontFamily: 'monospace',
            fontSize: 12,
            color: C.amber,
            fontWeight: 700
          }}>
            {meta?.id || activeOKF?.id || 'fiche.md'}
          </span>
          
          {/* Status Badge */}
          {(meta?.status || meta?.statut) && (
            <StatusBadge status={meta.status || meta.statut} />
          )}
          
          <div style={{
            marginLeft: 'auto',
            display: 'flex',
            gap: 4
          }}>
            {!readOnly && (
              <>
                <label style={{
                  ...btnStyle('ghost'),
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: 4,
                  padding: '4px 8px'
                }}>
                  <Icon.upload />
                  <span style={{ fontSize: 11 }}>Ouvrir</span>
                  <input
                    type="file"
                    accept=".md,.markdown"
                    style={{ display: 'none' }}
                    onChange={handleFileLoad}
                    ref={fileInputRef}
                  />
                </label>
                <button onClick={handleSave} style={btnStyle('ghost')}>
                  <Icon.save />
                </button>
              </>
            )}
            <button onClick={handleCopy} style={btnStyle('ghost')}>
              {copied ? <Icon.check /> : <Icon.copy />}
            </button>
          </div>
        </div>
        
        {/* Metadata */}
        {meta && (
          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
            {/* ref_document (new) or ref_rccm (old) */}
            {(meta.ref_document || meta.ref_rccm) && (
              <span style={{ fontSize: 11, color: C.muted }}>
                Document: <span style={{ color: C.blue }}>{meta.ref_document || meta.ref_rccm}</span>
              </span>
            )}
            
            {/* pages (new) or pages_pdf (old) */}
            {(meta.pages || meta.pages_pdf) && (
              <span style={{ fontSize: 11, color: C.muted }}>
                Pages: <span style={{ color: C.amber }}>{meta.pages?.raw || meta.pages_pdf?.raw}</span>
              </span>
            )}
            
            {/* version */}
            {meta.version && (
              <span style={{ fontSize: 11, color: C.muted }}>
                v{meta.version}
              </span>
            )}
            
            {/* author (new) or auteur (old) */}
            {(meta.author || meta.auteur) && (
              <span style={{ fontSize: 11, color: C.muted }}>
                {meta.author || meta.auteur}
              </span>
            )}
          </div>
        )}
        
        {/* Related links */}
        {(meta.related || meta.liens) && (
          <div style={{
            display: 'flex',
            gap: 4,
            marginTop: 4,
            flexWrap: 'wrap',
            alignItems: 'center'
          }}>
            <span style={{ fontSize: 10, color: C.muted }}>
              <Icon.link /> Liens:
            </span>
            {(meta.related || meta.liens || []).map(link => (
              <span key={link} style={{
                fontSize: 10,
                background: `${C.blue}11`,
                color: C.blue,
                borderRadius: 4,
                padding: '1px 6px',
                border: `1px solid ${C.blue}33`
              }}>
                {link}
              </span>
            ))}
          </div>
        )}
      </div>

      {/* Tabs */}
      <div style={{
        display: 'flex',
        borderBottom: `1px solid ${C.border}`,
        background: C.surface,
        flexShrink: 0
      }}>
        {(readOnly ? ['preview'] : ['edit', 'preview']).map(t => (
          <button
            key={t}
            onClick={() => setTab(t)}
            style={{
              padding: '6px 16px',
              fontSize: 12,
              background: 'transparent',
              border: 'none',
              cursor: 'pointer',
              fontFamily: 'system-ui',
              color: tab === t ? C.blue : C.muted,
              borderBottom: tab === t ? `2px solid ${C.blue}` : '2px solid transparent',
              transition: 'all .15s'
            }}
          >
            {t === 'edit' ? '✏️ Édition' : '👁 Aperçu'}
          </button>
        ))}
        {readOnly && (
          <span style={{
            marginLeft: 'auto',
            alignSelf: 'center',
            marginRight: 12,
            fontSize: 10,
            color: C.muted,
            fontFamily: 'monospace'
          }}>
            🔒 lecture seule
          </span>
        )}
      </div>

      {/* Content */}
      <div style={{ flex: 1, overflow: 'hidden' }}>
        {tab === 'edit' ? (
          <textarea
            value={content || ''}
            onChange={e => onChange(e.target.value)}
            style={{
              width: '100%',
              height: '100%',
              background: C.bg,
              border: 'none',
              color: C.text,
              fontFamily: 'monospace',
              fontSize: 12,
              lineHeight: 1.7,
              padding: '16px',
              resize: 'none',
              outline: 'none',
              boxSizing: 'border-box',
              tabSize: 2
            }}
            spellCheck={false}
          />
        ) : (
          <div style={{ height: '100%', overflowY: 'auto', padding: '16px' }}>
            <MarkdownPreview content={content} />
          </div>
        )}
      </div>
    </div>
  );
}
