// OKF Workspace Generic - PDFPanel Component
// Multi-PDF support with tabbed interface
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

import React, { useState, useEffect } from 'react';
import { C, btnStyle, Icon } from '../constants';

/**
 * PDFPanel - PDF viewer with multi-PDF support
 * 
 * Features:
 * - Multiple PDF tabs
 * - Page navigation
 * - Page range display from metadata
 * - Generic text (no RCC-M references)
 */
export default function PDFPanel({ 
  bundleConfig, 
  pdfFiles, 
  activePDFId, 
  setActivePDFById,
  currentPage, 
  setCurrentPage,
  activePDFRef,
  meta
}) {
  const fileInputRef = React.useRef(null);
  
  // ==========================================================================
  // STATE
  // ==========================================================================
  
  // Local PDF file (for single PDF mode, backward compatibility)
  const [pdfFile, setPdfFile] = useState(null);
  const [pdfUrl, setPdfUrl] = useState(null);

  // ==========================================================================
  // DERIVED STATE
  // ==========================================================================
  
  // Get active PDF from pdfFiles if in bundle mode
  const activePDF = activePDFId && pdfFiles[activePDFId] ? pdfFiles[activePDFId].file : null;
  const activePDFUrl = activePDFId && pdfFiles[activePDFId] ? pdfFiles[activePDFId].url : null;
  
  // Get page range from metadata or PDF reference
  const pageStart = meta?.pages?.start || activePDFRef?.pages?.start || 1;
  const pageEnd = meta?.pages?.end || activePDFRef?.pages?.end || 100;
  
  // Check if we're in bundle mode (multiple PDFs)
  const isBundleMode = bundleConfig && bundleConfig.pdfs && bundleConfig.pdfs.length > 0;

  // ==========================================================================
  // EFFECTS
  // ==========================================================================
  
  // Update current page when metadata changes
  useEffect(() => {
    if (meta?.pages?.start) {
      setCurrentPage(meta.pages.start);
    } else if (activePDFRef?.pages?.start) {
      setCurrentPage(activePDFRef.pages.start);
    }
  }, [meta?.pages?.start, activePDFRef?.pages?.start, setCurrentPage]);
  
  // Set initial PDF when bundle config changes
  useEffect(() => {
    if (isBundleMode && bundleConfig?.pdfs?.length > 0 && !activePDFId) {
      setActivePDFById(bundleConfig.pdfs[0].id);
    }
  }, [bundleConfig, isBundleMode, activePDFId, setActivePDFById]);

  // ==========================================================================
  // HANDLERS
  // ==========================================================================
  
  const handleFileLoad = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    
    // For backward compatibility (non-bundle mode)
    const url = URL.createObjectURL(file);
    setPdfUrl(url);
    setPdfFile(file.name);
    setCurrentPage(1);
  };
  
  const handleAddPDF = () => {
    fileInputRef.current?.click();
  };

  // ==========================================================================
  // RENDER
  // ==========================================================================

  return (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      height: '100%',
      background: C.bg
    }}>
      {/* Header - PDF Selector (Bundle Mode) or File Input (Legacy Mode) */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        padding: '8px 12px',
        background: C.surface,
        borderBottom: `1px solid ${C.border}`,
        flexShrink: 0
      }}>
        <Icon.pdf />
        
        {isBundleMode && bundleConfig?.pdfs?.length > 0 ? (
          <>
            {/* PDF Tabs */}
            <div style={{
              display: 'flex',
              gap: 2,
              flex: 1,
              overflowX: 'auto',
              paddingBottom: 2
            }}>
              {bundleConfig.pdfs.map((pdf, index) => (
                <button
                  key={pdf.id}
                  onClick={() => setActivePDFById(pdf.id)}
                  style={{
                    padding: '4px 8px',
                    fontSize: 11,
                    fontFamily: 'monospace',
                    background: activePDFId === pdf.id ? C.bg : 'transparent',
                    border: activePDFId === pdf.id ? `1px solid ${C.borderAct}` : `1px solid transparent`,
                    borderRadius: 4,
                    color: activePDFId === pdf.id ? C.text : C.muted,
                    cursor: 'pointer',
                    whiteSpace: 'nowrap',
                    borderBottom: activePDFId === pdf.id ? `2px solid ${C.amber}` : 'none'
                  }}
                  title={pdf.name}
                >
                  {pdf.name}
                </button>
              ))}
            </div>
            
            {/* Add PDF button */}
            <button onClick={handleAddPDF} style={btnStyle('secondary')}>
              <Icon.upload /> Ajouter
            </button>
          </>
        ) : (
          <>
            {/* Legacy Mode - Single PDF */}
            <span style={{
              fontFamily: 'monospace',
              fontSize: 12,
              color: C.muted,
              flex: 1,
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              whiteSpace: 'nowrap'
            }}>
              {pdfFile || activePDF?.name || "Aucun PDF chargé"}
            </span>
            <button onClick={handleAddPDF} style={btnStyle('secondary')}>
              <Icon.upload /> Ouvrir PDF
            </button>
          </>
        )}
        
        <input
          ref={fileInputRef}
          type="file"
          accept=".pdf"
          style={{ display: 'none' }}
          onChange={handleFileLoad}
        />
      </div>

      {/* Page Range Indicator */}
      {(meta?.pages || activePDFRef?.pages) && (
        <div style={{
          padding: '6px 12px',
          background: C.amberBg,
          borderBottom: `1px solid ${C.amber}33`,
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          flexShrink: 0
        }}>
          <span style={{ color: C.amber, fontSize: 11, fontFamily: 'monospace' }}>
            📌 Pages indiquées : <strong>{meta?.pages?.raw || activePDFRef?.pages?.raw || `${pageStart}-${pageEnd}`}</strong>
          </span>
          
          <div style={{ marginLeft: 'auto', display: 'flex', gap: 4 }}>
            {Array.from({ length: Math.min(pageEnd - pageStart + 1, 8) }, (_, i) => pageStart + i).map(p => (
              <button
                key={p}
                onClick={() => setCurrentPage(p)}
                style={{
                  ...btnStyle('ghost'),
                  padding: '1px 6px',
                  fontSize: 10,
                  color: currentPage === p ? C.amber : C.muted,
                  background: currentPage === p ? `${C.amber}22` : 'transparent',
                  border: currentPage === p ? `1px solid ${C.amber}44` : '1px solid transparent'
                }}
              >
                {p}
              </button>
            ))}
            {pageEnd - pageStart + 1 > 8 && (
              <span style={{ fontSize: 10, color: C.muted }}>
                +{pageEnd - pageStart - 7}
              </span>
            )}
          </div>
        </div>
      )}

      {/* Navigation Bar */}
      {(pdfUrl || activePDFUrl) && (
        <div style={{
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          padding: '6px 12px',
          background: C.surface,
          borderBottom: `1px solid ${C.border}`,
          flexShrink: 0
        }}>
          <button onClick={() => setCurrentPage(p => Math.max(1, p - 1))} style={btnStyle('ghost')}>
            <Icon.prev />
          </button>
          <span style={{ fontFamily: 'monospace', fontSize: 12, color: C.text }}>
            Page <strong style={{ color: C.blue }}>{currentPage}</strong>
          </span>
          <button onClick={() => setCurrentPage(p => p + 1)} style={btnStyle('ghost')}>
            <Icon.next />
          </button>
          <div style={{ marginLeft: 'auto', display: 'flex', gap: 4 }}>
            <span style={{ fontSize: 11, color: C.muted }}>Aller à :</span>
            <input
              type="number"
              value={currentPage}
              onChange={e => setCurrentPage(Number(e.target.value))}
              style={{
                width: 56,
                background: C.bg,
                border: `1px solid ${C.border}`,
                color: C.text,
                borderRadius: 4,
                padding: '2px 6px',
                fontFamily: 'monospace',
                fontSize: 12
              }}
            />
          </div>
        </div>
      )}

      {/* Main Content */}
      <div style={{ flex: 1, overflow: 'hidden' }}>
        {!pdfUrl && !activePDFUrl ? (
          /* No PDF loaded */
          <div style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            height: '100%',
            gap: 16
          }}>
            <div style={{
              width: 64,
              height: 64,
              borderRadius: 12,
              background: C.surface,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              border: `2px dashed ${C.border}`
            }}>
              <Icon.pdf style={{ width: 28, height: 28, fill: C.muted }} />
            </div>
            <div style={{ textAlign: 'center' }}>
              <div style={{ color: C.text, fontSize: 14, marginBottom: 4 }}>
                Charger un PDF de référence
              </div>
              {meta?.ref_document && (
                <div style={{ color: C.muted, fontSize: 12 }}>
                  Référence : <span style={{ color: C.amber }}>{meta.ref_document}</span>
                </div>
              )}
              {meta?.ref_rccm && (
                <div style={{ color: C.muted, fontSize: 12 }}>
                  Référence : <span style={{ color: C.amber }}>{meta.ref_rccm}</span>
                </div>
              )}
            </div>
            <button onClick={handleAddPDF} style={btnStyle('primary')}>
              <Icon.upload /> Ouvrir un PDF
            </button>
          </div>
        ) : (
          /* PDF loaded */
          <iframe
            src={`${activePDFUrl || pdfUrl}#page=${currentPage}`}
            style={{
              width: '100%',
              height: '100%',
              border: 'none',
              background: '#fff'
            }}
            title="Visionneuse PDF"
          />
        )}
      </div>
    </div>
  );
}
