// OKF Workspace Generic - SideFiles Component
// Editor for index.md and log.md files
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

import React, { useState } from 'react';
import { C, btnStyle } from '../constants';

/**
 * SideFiles - Editor for index.md and log.md
 * Occupies the lower part of the left column
 */
export default function SideFiles({ 
  indexContent, 
  logContent, 
  onIndexChange, 
  onLogChange, 
  readOnly 
}) {
  const [active, setActive] = useState('index');
  const fileInputRef = React.useRef(null);

  // ==========================================================================
  // HANDLERS
  // ==========================================================================

  const handleFileSave = (name, content) => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = name;
    a.click();
  };

  const handleFileLoad = (setter) => (e) => {
    const file = e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = ev => setter(ev.target.result);
    reader.readAsText(file);
  };

  // ==========================================================================
  // RENDER
  // ==========================================================================

  return (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      height: '100%',
      borderTop: `1px solid ${C.border}`
    }}>
      {/* Tabs */}
      <div style={{
        display: 'flex',
        background: C.surface,
        borderBottom: `1px solid ${C.border}`,
        flexShrink: 0
      }}>
        {[['index', '📋 index.md'], ['log', '📒 log.md']].map(([key, label]) => (
          <button
            key={key}
            onClick={() => setActive(key)}
            style={{
              flex: 1,
              padding: '5px 8px',
              fontSize: 11,
              background: 'transparent',
              border: 'none',
              cursor: 'pointer',
              fontFamily: 'monospace',
              color: active === key ? C.blue : C.muted,
              borderBottom: active === key ? `2px solid ${C.blue}` : '2px solid transparent'
            }}
          >
            {label}
          </button>
        ))}
        
        <div style={{ display: 'flex', gap: 2, padding: '4px 6px' }}>
          {!readOnly && (
            <label style={{ ...btnStyle('ghost'), cursor: 'pointer', padding: '2px 6px', fontSize: 10 }}>
              ↑
              <input
                type="file"
                accept=".md"
                style={{ display: 'none' }}
                onChange={handleFileLoad(active === 'index' ? onIndexChange : onLogChange)}
                ref={fileInputRef}
              />
            </label>
          )}
          <button
            onClick={() => handleFileSave(
              active === 'index' ? 'index.md' : 'log.md',
              active === 'index' ? indexContent : logContent
            )}
            style={{ ...btnStyle('ghost'), padding: '2px 6px', fontSize: 10 }}
          >
            ↓
          </button>
        </div>
      </div>

      {/* Content */}
      <textarea
        value={active === 'index' ? indexContent || '' : logContent || ''}
        onChange={e => !readOnly && (active === 'index' ? onIndexChange : onLogChange)(e.target.value)}
        readOnly={readOnly}
        style={{
          flex: 1,
          background: readOnly ? `${C.surface}cc` : C.bg,
          border: 'none',
          color: C.text,
          fontFamily: 'monospace',
          fontSize: 11,
          lineHeight: 1.6,
          padding: '10px',
          resize: 'none',
          outline: 'none',
          cursor: readOnly ? 'default' : 'text'
        }}
        spellCheck={false}
      />
    </div>
  );
}
