// OKF Workspace Generic - StatusBadge Component
// Supports both old (RCC-M) and new (generic) status values
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

import React from 'react';
import { C, STATUS_LABELS, STATUS_COLORS } from '../constants';

/**
 * StatusBadge - Displays status badge with appropriate color and label
 * 
 * Supports:
 * - New generic statuses: DRAFT, IN_REVIEW, VALIDATED, ARCHIVED
 * - Old RCC-M statuses: VALIDÉ, EN_COURS, BROUILLON
 */
export default function StatusBadge({ status }) {
  // Map old RCC-M statuses to new generic ones for display
  const statusMap = {
    // Old RCC-M statuses
    'VALIDÉ': 'VALIDATED',
    'EN_COURS': 'IN_REVIEW',
    'BROUILLON': 'DRAFT',
    // New generic statuses
    'DRAFT': 'DRAFT',
    'IN_REVIEW': 'IN_REVIEW',
    'VALIDATED': 'VALIDATED',
    'ARCHIVED': 'ARCHIVED'
  };
  
  // Get the normalized status
  const normalizedStatus = statusMap[status] || status;
  
  // Get display label (French)
  const label = STATUS_LABELS[normalizedStatus] || status || '—';
  
  // Get color configuration
  const colors = STATUS_COLORS[normalizedStatus] || { bg: C.surface, color: C.muted };
  
  return (
    <span style={{
      background: colors.bg,
      color: colors.color,
      border: `1px solid ${colors.color}44`,
      borderRadius: 4,
      fontSize: 10,
      fontWeight: 700,
      padding: '2px 8px',
      letterSpacing: 1,
      fontFamily: 'monospace'
    }}>
      {label}
    </span>
  );
}
