// OKF Workspace Generic - Bundle Storage Utilities
// Save and load bundle configurations and OKF files
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

import { BundleConfig, OKFFile, BundleJSON } from '../types';

// Short random suffix appended to Date.now()-based ids so two ids generated
// within the same millisecond (e.g. adding several PDFs in a loop) don't collide.
function uniqueSuffix(): string {
  return Math.random().toString(36).slice(2, 6);
}

/**
 * Save bundle to a downloadable JSON file
 * @param bundleConfig - Bundle configuration to save
 * @param okfFiles - Array of OKF files to save
 * @param fileName - Optional file name (defaults to bundle name)
 */
export function saveBundle(
  bundleConfig: BundleConfig | null,
  okfFiles: OKFFile[]
): void {
  if (!bundleConfig) {
    console.warn('Cannot save bundle: bundleConfig is null');
    return;
  }
  
  const bundleJSON: BundleJSON = {
    version: "1.0",
    bundle: bundleConfig,
    files: okfFiles
  };
  
  const jsonString = JSON.stringify(bundleJSON, null, 2);
  const blob = new Blob([jsonString], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = `${bundleConfig.name.replace(/[^a-z0-9]/gi, '_')}_bundle.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Load bundle from a JSON file
 * @param file - File object from input
 * @returns Promise resolving to { bundleConfig, okfFiles }
 */
export function loadBundle(file: File): Promise<{ bundleConfig: BundleConfig; okfFiles: OKFFile[] }> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    
    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;
        if (!content) {
          throw new Error('File is empty');
        }
        
        const data: BundleJSON = JSON.parse(content);
        
        // Validate bundle format
        if (!data.bundle || !data.files) {
          throw new Error('Invalid bundle format: missing bundle or files');
        }
        
        // Validate version
        if (data.version !== "1.0") {
          console.warn(`Bundle version ${data.version} may not be compatible`);
        }
        
        resolve({
          bundleConfig: data.bundle,
          okfFiles: data.files
        });
      } catch (err: any) {
        reject(new Error(`Failed to parse bundle: ${err.message}`));
      }
    };
    
    reader.onerror = () => {
      reject(new Error('Failed to read file'));
    };
    
    reader.readAsText(file);
  });
}

/**
 * Create a new bundle configuration
 * @param options - Bundle options
 * @returns BundleConfig object
 */
export function createBundleConfig(options: {
  name: string;
  description?: string;
  path?: string;
  pdfs?: Array<{ name: string; file?: File; pageRange?: { start: number; end: number } }>;
}): BundleConfig {
  const id = `bundle-${Date.now()}-${uniqueSuffix()}`;
  const now = new Date().toISOString();

  const pdfs = options.pdfs?.map((pdf, index) => ({
    id: `pdf-${Date.now()}-${index}-${uniqueSuffix()}`,
    name: pdf.name,
    path: pdf.name,
    pages: pdf.pageRange || { start: 1, end: 100, raw: "1-100" }
  })) || [];
  
  return {
    id,
    name: options.name,
    description: options.description || '',
    path: options.path || '',
    createdAt: now,
    updatedAt: now,
    pdfs
  };
}

/**
 * Create a new OKF file
 * @param options - OKF file options
 * @returns OKFFile object
 */
export function createOKFFile(options: {
  title: string;
  ref_document?: string;
  pages?: { start: number; end: number };
  status?: "DRAFT" | "IN_REVIEW" | "VALIDATED" | "ARCHIVED";
  version?: string;
  author?: string;
  tags?: string[];
  related?: string[];
  content?: string;
}): OKFFile {
  const id = `OKF-${Date.now()}-${uniqueSuffix()}`;
  const now = new Date().toISOString();
  
  // Build ref_document from options
  const ref_document = options.ref_document || '';
  
  // Build pages from options
  const pages = options.pages 
    ? { 
        start: options.pages.start,
        end: options.pages.end,
        raw: `${options.pages.start}-${options.pages.end}` 
      }
    : undefined;
  
  // Default status
  const status = options.status || "DRAFT";
  
  // Generate front-matter content if not provided
  let content = options.content || '';
  if (!content || !content.startsWith('---')) {
    const frontMatter = `---
id: ${id}
title: ${options.title}
ref_document: ${ref_document}
${pages ? `pages: ${pages.raw}` : ''}
status: ${status}
${options.version ? `version: ${options.version}` : ''}
${options.author ? `author: ${options.author}` : ''}
updated_at: ${now}
${options.tags?.length ? `tags: [${options.tags.join(', ')}]` : ''}
${options.related?.length ? `related:\n  ${options.related.map(r => `- ${r}`).join('\n  ')}` : ''}
---

# ${options.title}

`;
    content = frontMatter + (options.content || '');
  }
  
  return {
    id,
    title: options.title,
    ref_document,
    pages,
    status,
    version: options.version,
    author: options.author,
    updated_at: now,
    tags: options.tags,
    related: options.related,
    content
  };
}

/**
 * Export bundle to a ZIP file (placeholder - would require JSZip library)
 * For now, just saves individual files
 * @param bundleConfig - Bundle configuration
 * @param okfFiles - Array of OKF files
 */
export function exportBundleAsZIP(bundleConfig: BundleConfig | null, okfFiles: OKFFile[]): void {
  if (!bundleConfig) return;
  
  // Save bundle.json
  saveBundle(bundleConfig, okfFiles);
  
  // Save each OKF file
  okfFiles.forEach(okfFile => {
    const blob = new Blob([okfFile.content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${okfFile.id}.md`;
    a.click();
    URL.revokeObjectURL(url);
  });
  
  console.log('Bundle exported as individual files');
}

/**
 * Import bundle from ZIP file (placeholder)
 * @param file - ZIP file
 * @returns Promise - Would resolve to bundle data
 */
export function importBundleFromZIP(file: File): Promise<any> {
  console.warn('ZIP import not yet implemented - would require JSZip library');
  return Promise.reject(new Error('ZIP import not implemented'));
}
