// OKF Workspace Generic - Front-Matter Parser
// Supports both old (RCC-M) and new (generic) field names for backward compatibility
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

/**
 * Parses YAML front-matter from markdown content
 * Supports both old RCC-M field names and new generic field names
 * @param md - Markdown content with front-matter
 * @returns Parsed metadata object with normalized field names
 */
export function parseFrontMatter(md: string | undefined): Record<string, any> {
  if (!md) return {};

  // Extract front-matter block
  const match = md.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};

  const meta: Record<string, any> = {};
  const lines = match[1].split("\n");

  // Field name mapping: old -> new
  const fieldMapping: Record<string, string> = {
    'ref_rccm': 'ref_document',
    'pages_pdf': 'pages',
    'statut': 'status',
    'titre': 'title',
    'date_maj': 'updated_at',
    'auteur': 'author',
    'liens': 'related'
  };

  // Fields that may be serialized as YAML arrays (either inline "[a, b]"
  // or as a block with items on subsequent "- item" lines)
  const arrayFields = new Set(['related', 'liens', 'tags']);

  let i = 0;
  while (i < lines.length) {
    const trimmedLine = lines[i].trim();
    if (!trimmedLine || trimmedLine.startsWith('#')) { i++; continue; }

    // Split on first colon only (values can contain colons)
    const colonIndex = trimmedLine.indexOf(':');
    if (colonIndex === -1) { i++; continue; }

    const rawKey = trimmedLine.slice(0, colonIndex).trim();
    const rawValue = trimmedLine.slice(colonIndex + 1).trim();

    // Clean value: remove surrounding quotes and trim
    let value = rawValue.replace(/^["']|["']$/g, '').trim();

    // Get the normalized field name
    const normalizedKey = fieldMapping[rawKey] || rawKey;
    i++;

    // Special handling for pages/pages_pdf field
    if (rawKey === 'pages_pdf' || normalizedKey === 'pages') {
      const [start, end] = value.split('-').map(Number);
      meta.pages = {
        start: start || 1,
        end: end || start || 1,
        raw: value
      };
      // Also keep the old field for backward compatibility
      if (rawKey === 'pages_pdf') {
        meta.pages_pdf = meta.pages;
      }
      continue;
    }

    // Special handling for array fields (related/liens/tags): can be
    // inline "[a, b]", comma-separated, a single bare value, or a YAML
    // block where items live on following "- item" lines with no colon.
    if (rawKey === 'liens' || arrayFields.has(normalizedKey)) {
      let items: string[];
      if (value.startsWith('[')) {
        const arrayMatch = value.match(/\[(.*?)\]/);
        items = arrayMatch ? arrayMatch[1].split(',').map(v => v.trim()).filter(Boolean) : [];
      } else if (value === '') {
        // Consume subsequent "- item" lines belonging to this block
        items = [];
        while (i < lines.length && lines[i].trim().startsWith('-')) {
          items.push(lines[i].trim().replace(/^-/, '').trim());
          i++;
        }
      } else if (value.includes(',')) {
        items = value.split(',').map(v => v.trim());
      } else {
        items = [value];
      }
      meta[normalizedKey] = items;
      // Also keep the old field for backward compatibility
      if (rawKey !== normalizedKey) {
        meta[rawKey] = items;
      }
      continue;
    }

    // Default handling
    meta[normalizedKey] = value;
    // Also keep the old field for backward compatibility
    if (fieldMapping[rawKey] && rawKey !== normalizedKey) {
      meta[rawKey] = value;
    }
  }

  return meta;
}

/**
 * Generates front-matter YAML string from metadata object
 * Uses new generic field names
 * @param meta - Metadata object
 * @returns YAML front-matter string
 */
export function generateFrontMatter(meta: Record<string, any>): string {
  const lines: string[] = [];

  // Field order for consistent output
  const fieldOrder = [
    'id', 'title', 'ref_document', 'pages', 'status',
    'version', 'author', 'updated_at', 'tags', 'related'
  ];

  const pushField = (field: string, rawValue: any) => {
    let value = rawValue;

    if (field === 'pages' && typeof value === 'object' && value?.raw) {
      value = value.raw;
    }

    if (Array.isArray(value)) {
      if (value.length === 0) return;
      if (field === 'tags') {
        // Inline bracket form: tags: [a, b]
        lines.push(`${field}: [${value.join(', ')}]`);
      } else {
        // Block form so each item lands on its own "- item" line,
        // which is what parseFrontMatter expects to round-trip correctly
        lines.push(`${field}:`);
        value.forEach(v => lines.push(`  - ${v}`));
      }
      return;
    }

    if (value !== null && value !== undefined && value !== '') {
      lines.push(`${field}: ${value}`);
    }
  };

  for (const field of fieldOrder) {
    if (meta[field] !== undefined) {
      pushField(field, meta[field]);
    }
  }

  // Add any additional fields not in the standard order
  for (const [key, value] of Object.entries(meta)) {
    if (!fieldOrder.includes(key) && value !== undefined && value !== null && value !== '') {
      pushField(key, value);
    }
  }

  if (lines.length === 0) return '';
  return `---\n${lines.join('\n')}\n---\n\n`;
}

/**
 * Checks if a string looks like it contains front-matter
 * @param content - String to check
 * @returns Boolean
 */
export function hasFrontMatter(content: string): boolean {
  return content?.startsWith('---') && content.includes('\n---');
}

/**
 * Strips front-matter from markdown content
 * @param content - Markdown content
 * @returns Content without front-matter
 */
export function stripFrontMatter(content: string): string {
  if (!content) return content;
  const match = content.match(/^---[\s\S]*?\n---/);
  if (match) {
    return content.slice(match[0].length);
  }
  return content;
}
