// OKF Workspace - PDF Indexer for Qdrant
// Automatically indexes PDF documents into Qdrant for RAG
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

import {
  RAG_API_URL,
  QDRANT_COLLECTION,
  RAG_API_KEY,
  MISTRAL_EMBEDDINGS_URL
} from '../constants';

// PDF.js library reference (loaded from CDN in browser)
// In test environment, this will be undefined and functions will fail gracefully
let pdfjsLib: any = null;

// Flag to track if PDF.js is being loaded
let pdfjsLoadingPromise: Promise<any> | null = null;

// Tracks whether the Qdrant collection has already been verified/created
let collectionReady: Promise<void> | null = null;

/** Reset the cached collection-ready promise (for tests). */
export function _resetCollectionReady(): void {
  collectionReady = null;
}

/**
 * Ensure the Qdrant collection exists, creating it if necessary.
 * Uses mistral-embed dimension (1024) with cosine distance.
 * The result is cached so the check only runs once per session.
 */
export function ensureCollection(): Promise<void> {
  if (!RAG_API_URL || !QDRANT_COLLECTION) {
    return Promise.resolve();
  }
  if (collectionReady) return collectionReady;

  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (RAG_API_KEY) headers["Authorization"] = `Bearer ${RAG_API_KEY}`;

  collectionReady = fetch(`${RAG_API_URL}/collections/${QDRANT_COLLECTION}`, { headers })
    .then(resp => {
      if (resp.ok) return; // collection already exists
      if (resp.status !== 404) throw new Error(`Qdrant GET collection error: HTTP ${resp.status}`);

      // Collection does not exist — create it
      return fetch(`${RAG_API_URL}/collections/${QDRANT_COLLECTION}`, {
        method: "PUT",
        headers,
        body: JSON.stringify({
          vectors: { size: 1024, distance: "Cosine" }
        }),
      }).then(createResp => {
        if (!createResp.ok) {
          throw new Error(`Qdrant create collection error: HTTP ${createResp.status}`);
        }
        console.log(`Qdrant collection "${QDRANT_COLLECTION}" created (1024-dim, cosine).`);
      });
    })
    .catch(err => {
      // Reset so next call can retry
      collectionReady = null;
      throw err;
    });

  return collectionReady;
}

/**
 * Get PDF.js library, loading from CDN if not already loaded
 * @returns Promise resolving to PDF.js library
 */
function getPdfjs() {
  if (pdfjsLib) {
    return Promise.resolve(pdfjsLib);
  }
  
  if (pdfjsLoadingPromise) {
    return pdfjsLoadingPromise;
  }
  
  // Only load from CDN in browser environment (not in tests)
  if (typeof window !== 'undefined' && !window.location.href.includes('jsdom')) {
    pdfjsLoadingPromise = new Promise((resolve, reject) => {
      const script = document.createElement('script');
      script.src = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';
      script.onload = () => {
        // @ts-ignore
        pdfjsLib = window.pdfjsLib;
        if (pdfjsLib && pdfjsLib.GlobalWorkerOptions) {
          pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
        }
        resolve(pdfjsLib);
      };
      script.onerror = () => {
        // Reset so a subsequent call can retry
        pdfjsLoadingPromise = null;
        reject(new Error('Failed to load PDF.js from CDN'));
      };
      document.head.appendChild(script);
    });
  } else {
    // In test environment, return a mock that will fail gracefully
    pdfjsLoadingPromise = Promise.resolve(null);
  }
  
  return pdfjsLoadingPromise;
}

/**
 * Mistral API Key for embeddings (from environment)
 * Uses the same key as LLM if available
 */
const MISTRAL_API_KEY = import.meta.env.VITE_MISTRAL_API_KEY || 
  import.meta.env.VITE_LLM_API_KEY || "";

/**
 * Chunk size for text splitting (number of tokens)
 */
const CHUNK_SIZE = 500;

/**
 * Extract text from a PDF file
 * @param file - PDF File object
 * @returns Promise resolving to extracted text
 */
export async function extractTextFromPDF(file: File): Promise<string> {
  try {
    const pdfjs = await getPdfjs();
    
    if (!pdfjs) {
      throw new Error('PDF.js not available. PDF text extraction requires PDF.js library.');
    }
    
    const arrayBuffer = await file.arrayBuffer();
    const pdfData = new Uint8Array(arrayBuffer);
    
    const pdf = await pdfjs.getDocument(pdfData).promise;
    let fullText = '';
    
    for (let i = 1; i <= pdf.numPages; i++) {
      const page = await pdf.getPage(i);
      const textContent = await page.getTextContent();
      const pageText = textContent.items.map((item: any) => item.str).join(' ');
      fullText += pageText + '\n';
    }
    
    return fullText;
  } catch (err: any) {
    console.error('Failed to extract text from PDF:', err.message);
    throw err;
  }
}

/**
 * Split text into chunks of approximately CHUNK_SIZE tokens
 * Simple implementation: split by sentences/paragraphs, then by words
 * @param text - Text to chunk
 * @param chunkSize - Target chunk size in tokens (default: CHUNK_SIZE)
 * @returns Array of text chunks
 */
export function splitTextIntoChunks(text: string, chunkSize: number = CHUNK_SIZE): string[] {
  const chunks: string[] = [];
  
  // Split by double newlines first (paragraphs)
  const paragraphs = text.split('\n\n').filter(p => p.trim().length > 0);
  
  let currentChunk = '';
  
  for (const para of paragraphs) {
    const paraWords = para.split(/\s+/);
    
    for (const word of paraWords) {
      const testChunk = currentChunk ? `${currentChunk} ${word}` : word;
      
      // Simple token estimation: ~4 chars = 1 token
      if (testChunk.length / 4 <= chunkSize) {
        currentChunk = testChunk;
      } else {
        if (currentChunk) {
          chunks.push(currentChunk);
        }
        currentChunk = word;
      }
    }
  }
  
  if (currentChunk) {
    chunks.push(currentChunk);
  }
  
  return chunks;
}

/**
 * Get embedding from Mistral API for a text
 * @param text - Text to embed
 * @returns Promise resolving to embedding vector
 */
async function getMistralEmbedding(text: string): Promise<number[]> {
  if (!MISTRAL_API_KEY || !MISTRAL_EMBEDDINGS_URL) {
    throw new Error("Mistral API key or embeddings URL not configured");
  }
  
  try {
    const resp = await fetch(MISTRAL_EMBEDDINGS_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${MISTRAL_API_KEY}`,
      },
      body: JSON.stringify({
        model: "mistral-embed",
        input: text,
      }),
    });
    
    if (!resp.ok) {
      throw new Error(`Mistral embeddings API error: HTTP ${resp.status}`);
    }
    
    const data = await resp.json();
    if (data.data && data.data[0] && data.data[0].embedding) {
      return data.data[0].embedding;
    }
    throw new Error("Invalid response format from Mistral embeddings API");
  } catch (err: any) {
    console.warn("Failed to get Mistral embedding:", err.message);
    throw err;
  }
}

/**
 * Check if a PDF (by name) already exists in Qdrant
 * @param pdfName - Name of the PDF file
 * @returns Promise resolving to true if PDF exists in Qdrant
 */
export async function pdfExistsInQdrant(pdfName: string): Promise<boolean> {
  if (!RAG_API_URL || !QDRANT_COLLECTION) {
    return false;
  }
  
  try {
    await ensureCollection();
    const searchEndpoint = `${RAG_API_URL}/collections/${QDRANT_COLLECTION}/points/scroll`;
    const searchHeaders: Record<string, string> = {
      "Content-Type": "application/json",
    };
    if (RAG_API_KEY) {
      searchHeaders["Authorization"] = `Bearer ${RAG_API_KEY}`;
    }
    
    const resp = await fetch(searchEndpoint, {
      method: "POST",
      headers: searchHeaders,
      body: JSON.stringify({
        filter: {
          must: [{ key: "ref", match: { value: pdfName } }]
        },
        limit: 1,
        with_payload: false,
        with_vector: false
      }),
    });
    
    if (!resp.ok) {
      throw new Error(`Qdrant scroll error: HTTP ${resp.status}`);
    }
    
    const data = await resp.json();
    return (data.result?.points?.length || 0) > 0;
  } catch (err: any) {
    console.warn("Failed to check if PDF exists in Qdrant:", err.message);
    return false;
  }
}

/**
 * Index a PDF file into Qdrant
 * @param file - PDF File object
 * @param pdfName - Name of the PDF (for reference)
 * @param pdfId - Unique ID for the PDF
 * @param onProgress - Optional callback for progress updates
 * @returns Promise resolving when indexing is complete
 */
export async function indexPDFInQdrant(
  file: File,
  pdfName: string,
  pdfId: string,
  onProgress?: (progress: { current: number; total: number; status: string }) => void
): Promise<void> {
  if (!RAG_API_URL || !QDRANT_COLLECTION) {
    console.warn("Qdrant not configured: missing RAG_API_URL or QDRANT_COLLECTION");
    return;
  }
  
  try {
    // Check if already indexed
    const exists = await pdfExistsInQdrant(pdfName);
    if (exists) {
      if (onProgress) onProgress({ current: 0, total: 0, status: `PDF "${pdfName}" déjà indexé` });
      console.log(`PDF "${pdfName}" already indexed in Qdrant, skipping.`);
      return;
    }
    
    // Extract text from PDF
    if (onProgress) onProgress({ current: 0, total: 0, status: `Extraction du texte de "${pdfName}"...` });
    const text = await extractTextFromPDF(file);
    
    // Split into chunks
    const chunks = splitTextIntoChunks(text);
    if (onProgress) onProgress({ current: 0, total: chunks.length, status: `Découpage en ${chunks.length} chunks` });
    
    // Index each chunk
    const points: any[] = [];
    for (let i = 0; i < chunks.length; i++) {
      if (onProgress) onProgress({ current: i, total: chunks.length, status: `Indexation du chunk ${i + 1}/${chunks.length}` });
      
      const embedding = await getMistralEmbedding(chunks[i]);
      
      points.push({
        id: `${pdfId}-chunk-${i}`,
        vector: embedding,
        payload: {
          ref: pdfName,
          pdf_id: pdfId,
          text: chunks[i],
          chunk_index: i,
          total_chunks: chunks.length
        }
      });
    }
    
    // Upsert all points to Qdrant
    const upsertEndpoint = `${RAG_API_URL}/collections/${QDRANT_COLLECTION}/points`;
    const upsertHeaders: Record<string, string> = {
      "Content-Type": "application/json",
    };
    if (RAG_API_KEY) {
      upsertHeaders["Authorization"] = `Bearer ${RAG_API_KEY}`;
    }
    
    // Batch upsert (Qdrant supports up to 100 points per request)
    const BATCH_SIZE = 100;
    for (let i = 0; i < points.length; i += BATCH_SIZE) {
      const batch = points.slice(i, i + BATCH_SIZE);
      const resp = await fetch(upsertEndpoint, {
        method: "PUT",
        headers: upsertHeaders,
        body: JSON.stringify({ points: batch }),
      });
      
      if (!resp.ok) {
        throw new Error(`Qdrant upsert error: HTTP ${resp.status}`);
      }
    }
    
    if (onProgress) onProgress({ current: chunks.length, total: chunks.length, status: `Indexation terminée` });
    console.log(`Successfully indexed ${chunks.length} chunks from "${pdfName}" into Qdrant.`);
    
  } catch (err: any) {
    console.error(`Failed to index PDF "${pdfName}" in Qdrant:`, err.message);
    if (onProgress) onProgress({ current: 0, total: 0, status: `Erreur: ${err.message}` });
    throw err;
  }
}

/**
 * Remove a PDF from Qdrant index
 * @param pdfName - Name of the PDF to remove
 * @returns Promise resolving when removal is complete
 */
export async function removePDFFromQdrant(pdfName: string): Promise<void> {
  if (!RAG_API_URL || !QDRANT_COLLECTION) {
    console.warn("Qdrant not configured: missing RAG_API_URL or QDRANT_COLLECTION");
    return;
  }
  
  try {
    await ensureCollection();
    // Find all points with this ref
    const searchEndpoint = `${RAG_API_URL}/collections/${QDRANT_COLLECTION}/points/scroll`;
    const searchHeaders: Record<string, string> = {
      "Content-Type": "application/json",
    };
    if (RAG_API_KEY) {
      searchHeaders["Authorization"] = `Bearer ${RAG_API_KEY}`;
    }
    
    const resp = await fetch(searchEndpoint, {
      method: "POST",
      headers: searchHeaders,
      body: JSON.stringify({
        filter: {
          must: [{ key: "ref", match: { value: pdfName } }]
        },
        limit: 10000, // Max limit for scroll
        with_payload: false,
        with_vector: false
      }),
    });
    
    if (!resp.ok) {
      throw new Error(`Qdrant scroll error: HTTP ${resp.status}`);
    }
    
    const data = await resp.json();
    const pointIds = data.result?.points?.map((p: any) => p.id) || [];
    
    if (pointIds.length === 0) {
      console.log(`No points found for PDF "${pdfName}" in Qdrant.`);
      return;
    }
    
    // Delete all points
    const deleteEndpoint = `${RAG_API_URL}/collections/${QDRANT_COLLECTION}/points/delete`;
    const deleteResp = await fetch(deleteEndpoint, {
      method: "POST",
      headers: searchHeaders,
      body: JSON.stringify({
        points: pointIds,
      }),
    });
    
    if (!deleteResp.ok) {
      throw new Error(`Qdrant delete error: HTTP ${deleteResp.status}`);
    }
    
    console.log(`Removed ${pointIds.length} chunks for PDF "${pdfName}" from Qdrant.`);
    
  } catch (err: any) {
    console.error(`Failed to remove PDF "${pdfName}" from Qdrant:`, err.message);
    throw err;
  }
}
