// OKF Workspace Generic - RAG Utilities
// Generic RAG integration that works with any PDF documents
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

import { RAGRequest, RAGResponse, RAGChunk } from '../types';
import {
  RAG_API_URL,
  RAG_TOP_K,
  RAG_API_KEY,
  QDRANT_COLLECTION,
  MISTRAL_EMBEDDINGS_URL
} from '../constants';

/**
 * Mistral API Key for embeddings (from environment)
 * Uses the same key as LLM if available
 */
const MISTRAL_API_KEY = import.meta.env.VITE_MISTRAL_API_KEY || 
  import.meta.env.VITE_LLM_API_KEY || "";

/**
 * Build RAG query from metadata and user message
 * Uses generic ref_document field and bundle config for PDF references
 * @param meta - Parsed metadata from OKF file
 * @param userMessage - User's message
 * @param bundleConfig - Current bundle configuration
 * @returns Query string for RAG API
 */
export function buildRagQuery(
  meta: Record<string, any> | null,
  userMessage: string,
  bundleConfig: any | null
): string {
  // Collect references from multiple sources
  const refs: string[] = [];
  
  // 1. From metadata ref_document field (new generic field)
  if (meta?.ref_document) {
    refs.push(...meta.ref_document.split(',').map(r => r.trim()).filter(Boolean));
  }
  
  // 2. From metadata ref_rccm field (old field for backward compatibility)
  if (meta?.ref_rccm) {
    refs.push(...meta.ref_rccm.split(',').map(r => r.trim()).filter(Boolean));
  }
  
  // 3. From bundle config PDFs
  if (bundleConfig?.pdfs) {
    for (const pdf of bundleConfig.pdfs) {
      // Only include PDFs that are referenced in the metadata
      if (meta?.ref_document?.includes(pdf.name) || meta?.ref_rccm?.includes(pdf.name)) {
        if (!refs.includes(pdf.name)) {
          refs.push(pdf.name);
        }
      }
    }
  }
  
  // Build query combining references, title, and user message
  const parts: string[] = [];
  
  if (refs.length > 0) {
    parts.push(refs.join(', '));
  }
  
  if (meta?.title || meta?.titre) {
    parts.push(meta.title || meta.titre);
  }
  
  if (userMessage) {
    parts.push(userMessage);
  }
  
  return parts.filter(Boolean).join(' ');
}

/**
 * Get embeddings from Mistral API
 * @param text - Text to embed
 * @returns Promise resolving to embedding vector
 */
async function getMistralEmbedding(text: string): Promise<number[]> {
  if (!MISTRAL_API_KEY || !MISTRAL_EMBEDDINGS_URL) {
    throw new Error("Mistral API key or embeddings URL not configured");
  }
  
  try {
    const resp = await fetch(MISTRAL_EMBEDDINGS_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${MISTRAL_API_KEY}`,
      },
      body: JSON.stringify({
        model: "mistral-embed",
        input: text,
      }),
    });
    
    if (!resp.ok) {
      throw new Error(`Mistral embeddings API error: HTTP ${resp.status}`);
    }
    
    const data = await resp.json();
    // Mistral returns: { data: [{ embedding: [...] }] }
    if (data.data && data.data[0] && data.data[0].embedding) {
      return data.data[0].embedding;
    }
    throw new Error("Invalid response format from Mistral embeddings API");
  } catch (err: any) {
    console.warn("Failed to get Mistral embedding:", err.message);
    throw err;
  }
}

/**
 * Fetch chunks from Qdrant
 * Uses Qdrant's native API: /collections/{name}/points/search
 * @param meta - Parsed metadata
 * @param userMessage - User's message
 * @param bundleConfig - Current bundle configuration
 * @returns Promise resolving to array of chunks
 */
export async function fetchRagChunks(
  meta: Record<string, any> | null,
  userMessage: string,
  bundleConfig: any | null
): Promise<RAGChunk[]> {
  if (!RAG_API_URL || !QDRANT_COLLECTION) {
    console.warn("Qdrant not configured: missing RAG_API_URL or QDRANT_COLLECTION");
    return [];
  }
  
  // Get refs for filtering
  const refs: string[] = [];
  if (meta?.ref_document) {
    refs.push(...meta.ref_document.split(',').map(r => r.trim()).filter(Boolean));
  }
  if (meta?.ref_rccm) {
    refs.push(...meta.ref_rccm.split(',').map(r => r.trim()).filter(Boolean));
  }
  if (bundleConfig?.pdfs) {
    for (const pdf of bundleConfig.pdfs) {
      if (!refs.includes(pdf.name)) {
        refs.push(pdf.name);
      }
    }
  }
  
  // Get pages from metadata (for context, not used in Qdrant search)
  const pages = meta?.pages || meta?.pages_pdf || null;
  
  try {
    // 1. Get embedding for the query
    const queryEmbedding = await getMistralEmbedding(userMessage);
    
    // 2. Build Qdrant filter from refs
    // If we have refs, filter by them; otherwise, search all
    const filter = refs.length > 0 ? {
      must: refs.map(ref => ({
        key: "ref",
        match: { value: ref }
      }))
    } : undefined;
    
    // 3. Search in Qdrant
    const searchEndpoint = `${RAG_API_URL}/collections/${QDRANT_COLLECTION}/points/search`;
    const searchBody = {
      vector: queryEmbedding,
      limit: RAG_TOP_K,
      filter: filter,
      with_payload: true,
      with_vector: false
    };
    
    const searchHeaders: Record<string, string> = {
      "Content-Type": "application/json",
    };
    if (RAG_API_KEY) {
      searchHeaders["Authorization"] = `Bearer ${RAG_API_KEY}`;
    }
    
    const resp = await fetch(searchEndpoint, {
      method: "POST",
      headers: searchHeaders,
      body: JSON.stringify(searchBody),
    });
    
    if (!resp.ok) {
      throw new Error(`Qdrant search error: HTTP ${resp.status}`);
    }
    
    const data = await resp.json();
    
    // 4. Format Qdrant response to RAGChunk[]
    // Qdrant returns: { result: { points: [{ id, payload, score }] } }
    const points = data.result?.points || [];
    
    return points.map((point: any, index: number) => ({
      id: point.id.toString() || `chunk-${index}`,
      ref: point.payload?.ref || "unknown",
      page_start: point.payload?.page_start || pages?.start || 1,
      page_end: point.payload?.page_end || pages?.end || 1,
      text: point.payload?.text || point.payload?.content || "",
      score: point.score || 0
    }));
    
  } catch (err: any) {
    console.warn("Qdrant RAG retrieval failed:", err.message);
    return [];
  }
}

/**
 * Format chunks for injection into system prompt
 * @param chunks - Array of RAG chunks
 * @returns Formatted string for system prompt, or null if no chunks
 */
export function formatChunksForPrompt(chunks: RAGChunk[]): string | null {
  if (!chunks.length) return null;
  
  return chunks.map((c, i) =>
    `--- Chunk ${i+1} | ${c.ref || "?"} | pp.${c.page_start ?? "?"}–${c.page_end ?? "?"} | score ${c.score != null ? c.score.toFixed(2) : "—"} ---\n${c.text}`
  ).join("\n\n");
}

/**
 * Build generic system prompt for LLM
 * @param meta - Parsed metadata
 * @param okfContent - Current OKF file content
 * @param indexContent - Index file content
 * @param logContent - Log file content
 * @param bundleConfig - Current bundle configuration
 * @param chunksBlock - Formatted chunks from RAG
 * @param readOnly - Whether in read-only mode
 * @returns System prompt string
 */
export function buildSystemPrompt(
  meta: Record<string, any>,
  okfContent: string,
  indexContent: string,
  logContent: string,
  bundleConfig: any | null,
  chunksBlock: string | null,
  readOnly: boolean
): string {
  // Generic system prompt (not RCC-M specific)
  const basePrompt = `Tu es un assistant expert pour l'analyse de documentation technique.
Tu aides à maintenir des fiches OKF (Objets de Connaissance Fondamentale) basées sur des documents PDF de référence.`;
  
  // Build document context
  const docContext = bundleConfig?.pdfs?.map(p => `• ${p.name}`).join("\n") || "Aucun document chargé";
  
  // Build chunks section
  const chunksSection = chunksBlock 
    ? `
=== EXTRAITS DES DOCUMENTS — SOURCE PRIMAIRE (base RAG) ===
Ces passages sont extraits directement des documents PDF chargés :
${docContext}

Appuie-toi prioritairement sur ces extraits pour répondre aux questions techniques.
Cite la référence du document et les pages lorsque tu t'y réfères.

${chunksBlock}
`
    : '';
  
  // Build OKF bundle context
  const okfContext = `
=== BUNDLE OKF — CONTEXTE DE NAVIGATION ===

--- FICHE ACTIVE (fiche.md) ---
${okfContent}

--- INDEX (index.md) ---
${indexContent}

--- JOURNAL (log.md) ---
${logContent}
`;
  
  // Build instructions based on mode
  const instructions = readOnly
    ? `
MODE LECTURE SEULE : Réponds aux questions en t'appuyant sur les extraits des documents et les fiches OKF. N'émets pas de blocs EDITS. Tu peux signaler des incohérences sans proposer de modifications.`
    : `
INSTRUCTIONS :
- Réponds en français, de manière concise et professionnelle
- Pour les questions techniques, cite les extraits injectés (ref + pages)
- Quand tu proposes des modifications aux fiches, encadre le JSON dans <EDITS>...</EDITS> :
{
  "fiche": "contenu complet si modifié, sinon null",
  "index": "contenu complet si modifié, sinon null",
  "log": "contenu complet si modifié, sinon null",
  "summary": "résumé en 1-2 phrases"
}
- Explique toujours tes modifications avant le bloc EDITS
- Pour log.md, ajoute en haut avec la date d'aujourd'hui`;
  
  return `${basePrompt}${chunksSection}${okfContext}${instructions}`;
}

/**
 * Get RAG status based on availability and state
 * @param ragApiUrl - RAG API URL from constants
 * @param chunks - Array of chunks
 * @param loading - Whether currently loading
 * @returns Status string: "idle" | "loading" | "ok" | "error" | "disabled"
 */
export function getRagStatus(ragApiUrl: string, chunks: RAGChunk[], loading: boolean): string {
  if (!ragApiUrl) return "disabled";
  if (loading) return "loading";
  if (chunks.length > 0) return "ok";
  return "idle";
}

/**
 * Get RAG indicator label
 * @param status - RAG status
 * @param count - Number of chunks
 * @returns Label string
 */
export function getRagIndicatorLabel(status: string, count: number): string {
  const labels: Record<string, string> = {
    idle: "RAG en attente",
    loading: "Retrieval…",
    ok: `${count} chunk${count > 1 ? "s" : ""} injecté${count > 1 ? "s" : ""}`,
    error: "RAG indisponible",
    disabled: "RAG non configuré"
  };
  return labels[status] || labels.idle;
}
