// OKF Workspace Generic - Constants and Sample Data
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

// ============================================================================
// CONFIGURATION LLM & RAG
// ============================================================================

// Chargement depuis les variables d'environnement (Vite)
// Les valeurs par défaut sont utilisées si les variables ne sont pas définies

// Configuration LLM
// Priorité pour l'URL : VITE_LLM_API_URL > "https://api.anthropic.com/v1/messages"
export const LLM_API_URL = import.meta.env.VITE_LLM_API_URL || "https://api.anthropic.com/v1/messages";
// Modèle par défaut
export const LLM_MODEL = import.meta.env.VITE_LLM_MODEL || "claude-sonnet-4-6";
// Priorité pour la clé API : VITE_LLM_API_KEY > VITE_MISTRAL_API_KEY > VITE_ANTHROPIC_API_KEY > VITE_OPENAI_API_KEY > ""
export const LLM_API_KEY = import.meta.env.VITE_LLM_API_KEY ||
  import.meta.env.VITE_MISTRAL_API_KEY ||
  import.meta.env.VITE_ANTHROPIC_API_KEY ||
  import.meta.env.VITE_OPENAI_API_KEY || "";

// Configuration RAG avec Qdrant
// Qdrant URL base (ex: http://localhost:6333)
export const RAG_API_URL = import.meta.env.VITE_RAG_API_URL || "";

// Nom de la collection Qdrant à interroger
export const QDRANT_COLLECTION = import.meta.env.VITE_QDRANT_COLLECTION || "okf_documents";

// Nombre de résultats à retourner
export const RAG_TOP_K = parseInt(import.meta.env.VITE_RAG_TOP_K || "5", 10);

// Clé API pour Qdrant (optionnelle, Qdrant n'en nécessite pas par défaut)
// Priorité : VITE_RAG_API_KEY > VITE_MISTRAL_API_KEY > ""
export const RAG_API_KEY = import.meta.env.VITE_RAG_API_KEY ||
  import.meta.env.VITE_MISTRAL_API_KEY || "";

// URL de l'API Mistral Embeddings (pour vectoriser les requêtes)
export const MISTRAL_EMBEDDINGS_URL = import.meta.env.VITE_MISTRAL_EMBEDDINGS_URL || 
  "https://api.mistral.ai/v1/embeddings";

// ============================================================================
// PALETTE & DESIGN
// ============================================================================

export const C = {
  bg: "#0d1117",       // fond général (noir bleuté)
  surface: "#161b22",   // surfaces secondaires (headers, panneaux)
  border: "#21262d",   // bordures
  borderAct: "#388bfd",
  text: "#e6edf3",     // texte principal
  muted: "#8b949e",     // texte secondaire / labels
  amber: "#d29922",     // accent principal (titres OKF, actions primaires)
  amberBg: "#1a1500",   // fond ambre très sombre (bandeau pages PDF)
  green: "#3fb950",     // statut VALIDATED, confirmations
  red: "#f85149",       // erreurs
  blue: "#388bfd",      // liens, onglets actifs, badge ID fiche
  blueDim: "#1f3358",   // fond bulle utilisateur dans le chat
  purple: "#bc8cff",    // statut DRAFT
};

// ============================================================================
// SAMPLE DATA - Backward Compatible (Old RCC-M Format)
// Not used by any app code path — kept only as a fixture for
// parseFrontMatter's backward-compatibility tests (real RCC-M-shaped
// front-matter, as opposed to synthetic strings written by hand).
// ============================================================================

export const SAMPLE_OKF = `---
id: OKF-2024-003
titre: Contrôle des soudures bout-à-bout
ref_rccm: B5300, B5310, B5320
pages_pdf: 142-158
statut: EN_COURS
version: 1.2
date_maj: 2024-06-15
auteur: J. Martin
tags: [soudure, contrôle, END]
liens:
  - OKF-2024-001
  - OKF-2024-007
---

# OKF-2024-003 — Contrôle des soudures bout-à-bout

## Objet
Définir les exigences de contrôle non-destructif applicables aux soudures bout-à-bout
conformément au RCC-M Tome I, Livre B, Chapitre B5300.

## Domaine d'application
- Composants de classe 1, 2 et 3
- Soudures de tuyauteries DN ≥ 50 mm
- Soudures de viroles et fonds

## Références normatives
| Paragraphe | Objet |
|------------|-------|
| B5300      | Généralités contrôle END |
| B5310      | Contrôle par ultrasons |
| B5320      | Contrôle radiographique |

## Exigences principales
1. Qualification des opérateurs selon RCC-M B5110
2. Procédures de contrôle approuvées avant exécution
3. Compte-rendu de contrôle archivé 30 ans

## Actions en cours
- [ ] Révision tableau B5310 suite à amendement 2024
- [ ] Mise à jour lien vers OKF-2024-001 (procédure parent)
- [ ] Validation par expert END

## Historique
| Version | Date | Modification |
|---------|------|--------------|
| 1.0 | 2024-01-10 | Création initiale |
| 1.1 | 2024-03-22 | Ajout tableau références |
| 1.2 | 2024-06-15 | EN COURS |
`;

// ============================================================================
// SAMPLE DATA - New Generic Format
// ============================================================================

export const SAMPLE_BUNDLE_CONFIG = {
  id: "bundle-2026-001",
  name: "Normes ISO 9001",
  description: "Système de management de la qualité",
  path: "/home/user/Documents/Projets/ISO_9001",
  createdAt: "2026-07-27T10:00:00Z",
  updatedAt: "2026-07-27T10:00:00Z",
  pdfs: [
    {
      id: "pdf-001",
      name: "ISO_9001_2015.pdf",
      path: "ISO_9001_2015.pdf",
      pages: { start: 10, end: 50, raw: "10-50" }
    },
    {
      id: "pdf-002",
      name: "ISO_9000_2015.pdf",
      path: "ISO_9000_2015.pdf",
      pages: { start: 1, end: 100, raw: "1-100" }
    }
  ]
};

export const SAMPLE_OKF_FILES = [
  {
    id: "OKF-2026-001",
    title: "Exigence de traçabilité",
    ref_document: "ISO_9001_2015.pdf",
    pages: { start: 10, end: 25, raw: "10-25" },
    status: "DRAFT",
    version: "1.0",
    author: "Jean Dupont",
    tags: ["traçabilité", "qualité", "ISO"],
    related: ["OKF-2026-002"],
    content: `---
id: OKF-2026-001
title: Exigence de traçabilité
ref_document: ISO_9001_2015.pdf
pages: 10-25
status: DRAFT
version: 1.0
author: Jean Dupont
tags: [traçabilité, qualité, ISO]
related:
  - OKF-2026-002
---

# OKF-2026-001 — Exigence de traçabilité

## Objet
Définir les exigences de traçabilité conformément à la norme ISO 9001:2015.

## Domaine d'application
- Tous les produits et services
- Processus de production et de livraison

## Exigences principales
1. Identification unique de tous les produits
2. Traçabilité tout au long du cycle de vie
3. Archivage des enregistrements pendant 10 ans

## Actions en cours
- [ ] Vérification de la conformité avec l'audit interne
- [ ] Mise à jour de la documentation

## Historique
| Version | Date | Modification |
|---------|------|--------------|
| 1.0 | 2026-07-27 | Création initiale |
`
  },
  {
    id: "OKF-2026-002",
    title: "Audit interne",
    ref_document: "ISO_9001_2015.pdf",
    pages: { start: 30, end: 45, raw: "30-45" },
    status: "IN_REVIEW",
    version: "1.0",
    author: "Jean Dupont",
    tags: ["audit", "qualité", "ISO"],
    related: ["OKF-2026-001"],
    content: `---
id: OKF-2026-002
title: Audit interne
ref_document: ISO_9001_2015.pdf
pages: 30-45
status: IN_REVIEW
version: 1.0
author: Jean Dupont
tags: [audit, qualité, ISO]
related:
  - OKF-2026-001
---

# OKF-2026-002 — Audit interne

## Objet
Définir la méthodologie d'audit interne pour le système de management de la qualité.

## Fréquence
- Audit annuel complet
- Audits partiels semestriels

## Critères d'audit
1. Conformité aux procédures documentées
2. Efficacité des processus
3. Opportunités d'amélioration
`
  },
  {
    id: "OKF-2026-003",
    title: "Revue de direction",
    ref_document: "ISO_9001_2015.pdf",
    pages: { start: 50, end: 60, raw: "50-60" },
    status: "VALIDATED",
    version: "1.0",
    author: "Jean Dupont",
    tags: ["revue", "direction", "ISO"],
    related: [],
    content: `---
id: OKF-2026-003
title: Revue de direction
ref_document: ISO_9001_2015.pdf
pages: 50-60
status: VALIDATED
version: 1.0
author: Jean Dupont
tags: [revue, direction, ISO]
---

# OKF-2026-003 — Revue de direction

## Objet
Processus de revue de direction pour évaluer la performance du SMQ.

## Participants
- Direction générale
- Responsable qualité
- Représentants des départements

## Sorties
- Décisions documentées
- Plan d'action
- Allocation des ressources
`
  }
];

// ============================================================================
// SAMPLE GENERIC INDEX
// ============================================================================

export const SAMPLE_GENERIC_INDEX = `# index.md — Registre des fiches OKF

| ID | Titre | Statut | Pages | Documents | Liens |
|----|-------|--------|-------|-----------|-------|
| OKF-2026-001 | Exigence de traçabilité | DRAFT | 10-25 | ISO_9001_2015.pdf | OKF-2026-002 |
| OKF-2026-002 | Audit interne | IN_REVIEW | 30-45 | ISO_9001_2015.pdf | OKF-2026-001 |
| OKF-2026-003 | Revue de direction | VALIDATED | 50-60 | ISO_9001_2015.pdf | - |
`;

// ============================================================================
// SAMPLE GENERIC LOG
// ============================================================================

export const SAMPLE_GENERIC_LOG = `# log.md — Journal des modifications

## 2026-07-27
- [OKF-2026-001] v1.0 — Création initiale
- [OKF-2026-002] v1.0 — Création initiale
- [OKF-2026-003] v1.0 — Création initiale
- [index.md] Mise à jour registre avec nouvelles fiches

## 2026-07-26
- Bundle "Normes ISO 9001" créé
- PDFs chargés: ISO_9001_2015.pdf, ISO_9000_2015.pdf
`;

// ============================================================================
// STATUS DISPLAY MAPPING (English enum -> French label)
// ============================================================================

export const STATUS_LABELS = {
  DRAFT: "BROUILLON",
  IN_REVIEW: "EN REVUE",
  VALIDATED: "VALIDÉ",
  ARCHIVED: "ARCHIVÉ"
};

export const STATUS_COLORS = {
  DRAFT: { bg: "#1a0f1a", color: "#bc8cff" },
  IN_REVIEW: { bg: "#1a1500", color: "#d29922" },
  VALIDATED: { bg: "#0d2a1a", color: "#3fb950" },
  ARCHIVED: { bg: "#1a1500", color: "#8b949e" }
};

// ============================================================================
// ICONS (SVG Components)
// ============================================================================

export const Icon = {
  file: () => <svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M2 1.75C2 .784 2.784 0 3.75 0h6.586c.464 0 .909.184 1.237.513l2.914 2.914c.329.328.513.773.513 1.237v9.586A1.75 1.75 0 0 1 13.25 16h-9.5A1.75 1.75 0 0 1 2 14.25V1.75zm1.75-.25a.25.25 0 0 0-.25.25v12.5c0 .138.112.25.25.25h9.5a.25.25 0 0 0 .25-.25V6h-2.75A1.75 1.75 0 0 1 9 4.25V1.5H3.75zm6.75.56v2.19c0 .138.112.25.25.25h2.19L10.5 2.06z"/></svg>,
  pdf: () => <svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5L9.5 0H4zm5.5 1.5v3h3L9.5 1.5zM2.5 2A1.5 1.5 0 0 1 4 .5h5v4h4v9.5A1.5 1.5 0 0 1 11.5 15.5h-7A1.5 1.5 0 0 1 3 14V2.5z"/></svg>,
  chat: () => <svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2a11 11 0 0 0 2.205-.306A1 1 0 0 1 5.5 14.5c0 .068-.007.135-.02.2L5.5 15l.017-.003A8.5 8.5 0 0 0 14 8.5C14 4.358 10.642 1 6.5 1 2.357 1 0 4.358 0 8.5c0 1.564.454 3.02 1.227 4.25a1 1 0 0 1 .228.569l.223 2.575zM0 8.5C0 3.806 2.806 0 6.5 0S13 3.806 13 8.5c0 2.117-.7 4.07-1.87 5.624a1 1 0 0 1-.155.176l-.012.01c-.21.18-.449.337-.704.47A9.5 9.5 0 0 1 6.5 16c-.91 0-1.785-.12-2.614-.346a1 1 0 0 1-.29-.134l-.02-.016-.021-.013-.005-.004-.001-.001a1 1 0 0 1-.394-.765l-.252-2.902A9.3 9.3 0 0 1 0 8.5z"/></svg>,
  send: () => <svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576zm6.787-8.201L1.591 6.602l4.339 2.76z"/></svg>,
  copy: () => <svg width="12" height="12" viewBox="0 0 16 16" fill="currentColor"><path d="M0 6.75C0 5.784.784 5 1.75 5h1.5a.75.75 0 0 1 0 1.5h-1.5a.25.25 0 0 0-.25.25v7.5c0 .138.112.25.25.25h7.5a.25.25 0 0 0 .25-.25v-1.5a.75.75 0 0 1 1.5 0v1.5A1.75 1.75 0 0 1 9.25 16h-7.5A1.75 1.75 0 0 1 0 14.25Z"/><path d="M5 1.75C5 .784 5.784 0 6.75 0h7.5C15.216 0 16 .784 16 1.75v7.5A1.75 1.75 0 0 1 14.25 11h-7.5A1.75 1.75 0 0 1 5 9.25Zm1.75-.25a.25.25 0 0 0-.25.25v7.5c0 .138.112.25.25.25h7.5a.25.25 0 0 0 .25-.25v-7.5a.25.25 0 0 0-.25-.25Z"/></svg>,
  prev: () => <svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/></svg>,
  next: () => <svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/></svg>,
  link: () => <svg width="12" height="12" viewBox="0 0 16 16" fill="currentColor"><path d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1 1 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4 4 0 0 1-.128-1.287z"/><path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243z"/></svg>,
  check: () => <svg width="12" height="12" viewBox="0 0 16 16" fill="currentColor"><path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/></svg>,
  upload: () => <svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/><path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z"/></svg>,
  save: () => <svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v7.293l2.646-2.647a.5.5 0 0 1 .708.708l-3.5 3.5a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L7.5 9.293V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/></svg>,
  rag: () => <svg width="13" height="13" viewBox="0 0 16 16" fill="currentColor"><path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/></svg>,
};

// ============================================================================
// STYLE HELPERS
// ============================================================================

export function btnStyle(variant) {
  const base = {
    display: "inline-flex", alignItems: "center", gap: 5,
    borderWidth: 1, borderStyle: "solid", borderRadius: 6, cursor: "pointer",
    fontSize: 12, fontFamily: "system-ui", padding: "4px 10px",
    transition: "all .15s", whiteSpace: "nowrap",
  };
  if (variant === "primary")   return { ...base, background: C.amber, color: "#0d0d0d", borderColor: C.amber, fontWeight: 700 };
  if (variant === "secondary") return { ...base, background: C.surface, color: C.text, borderColor: C.border };
  return { ...base, background: "transparent", color: C.muted, borderColor: "transparent" };
}
