// OKF Workspace Generic - TypeScript Type Definitions
// Generated by Mistral Vibe
// Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

/**
 * Bundle Configuration - Represents a workspace bundle containing multiple PDFs and OKF files
 */
export interface BundleConfig {
  id: string;                    // Unique bundle identifier (e.g., "bundle-2026-001")
  name: string;                  // Bundle name/project title (e.g., "Normes ISO 9001")
  description?: string;          // Optional description
  path: string;                  // Local folder path
  createdAt: string;             // Creation timestamp (ISO 8601)
  updatedAt: string;             // Last update timestamp (ISO 8601)
  pdfs: PDFReference[];          // Array of PDF references
}

/**
 * PDF Reference - Represents a single PDF document within a bundle
 */
export interface PDFReference {
  id: string;                    // Unique PDF identifier (e.g., "pdf-001")
  name: string;                  // PDF filename (e.g., "ISO_9001_2015.pdf")
  path: string;                  // Relative or absolute path
  pages: { 
    start: number; 
    end: number; 
    raw: string 
  };                           // Page range
}

/**
 * OKF File - Represents a single OKF (Objet de Connaissance Fondamentale) file
 */
export interface OKFFile {
  id: string;                    // Unique OKF identifier (e.g., "OKF-2026-001")
  title: string;                 // OKF title
  ref_document: string;          // Reference(s) to PDF document(s), comma-separated
  pages?: { 
    start: number; 
    end: number; 
    raw: string 
  };                           // Optional page range
  status: "DRAFT" | "IN_REVIEW" | "VALIDATED" | "ARCHIVED";  // Generic status enum
  version?: string;              // Optional version
  author?: string;               // Optional author
  updated_at?: string;           // Optional last update timestamp
  tags?: string[];               // Optional keywords/tags
  related?: string[];            // Optional IDs of related OKF files
  content: string;               // Markdown content with front-matter
}

/**
 * Application State - Complete state of the OKF Workspace
 */
export interface AppState {
  // Bundle configuration
  bundleConfig: BundleConfig | null;
  
  // OKF files
  okfFiles: OKFFile[];
  activeOKFId: string | null;
  
  // PDF files
  pdfFiles: Record<string, { file: File; url: string }>;  // { pdfId: {file, url} }
  activePDFId: string | null;
  currentPage: number;
  
  // UI state
  layout: "3col" | "focus-okf" | "focus-pdf";
  readOnly: boolean;
  
  // Initializer modal
  showInitializer: boolean;
}

/**
 * Metadata parsed from OKF file front-matter
 * Supports both old (RCC-M) and new (generic) field names for backward compatibility
 */
export interface ParsedMetadata {
  // New generic fields
  id?: string;
  title?: string;
  ref_document?: string;
  pages?: { start: number; end: number; raw: string };
  status?: string;
  version?: string;
  author?: string;
  updated_at?: string;
  tags?: string[];
  related?: string[];
  
  // Old RCC-M fields (for backward compatibility)
  ref_rccm?: string;
  pages_pdf?: { start: number; end: number; raw: string };
  statut?: string;
  titre?: string;
  date_maj?: string;
  auteur?: string;
  liens?: string[];
}

/**
 * Chunk from RAG API response
 */
export interface RAGChunk {
  id: string;
  ref: string;                  // Document reference
  page_start: number;
  page_end: number;
  text: string;                 // Extracted text content
  score: number;                // Similarity score (0-1)
}

/**
 * RAG API Request
 */
export interface RAGRequest {
  query: string;
  refs: string[];
  pages: { start: number; end: number } | null;
  top_k: number;
}

/**
 * RAG API Response
 */
export interface RAGResponse {
  chunks: RAGChunk[];
}

/**
 * Message in chat conversation
 */
export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
  edits?: {
    fiche?: string;
    index?: string;
    log?: string;
    summary?: string;
  };
  chunks?: RAGChunk[];
}

/**
 * Initializer Modal Step
 */
export type InitializerStep = "folder" | "name" | "pdfs" | "confirm";

/**
 * Initializer Modal State
 */
export interface InitializerState {
  step: InitializerStep;
  selectedPath: string | null;
  bundleName: string;
  bundleDescription: string;
  selectedPDFs: File[];
  pdfRanges: Record<string, { start: number; end: number }>;
}

/**
 * Bundle JSON file format for save/load
 */
export interface BundleJSON {
  version: string;
  bundle: BundleConfig;
  files: OKFFile[];
}
